namespace SharbatlyQMS.Web.Models;

/// <summary>
/// SEED data for SAP plant + storage-location descriptive names, supplied by
/// the operator on 2026-06-15 (snapshot of the live SAP configuration tables)
/// so the QMS UI can render "JD01 — Jeddah" / "JDCS — JD Main Coldstor"
/// instead of bare codes.
///
/// This used to BE the lookup: a hard-coded file that needed a redeploy to
/// change. Since M10 the live source is qms_code_description, editable from
/// Parameters &gt; Code Descriptions, and these 562 rows were seeded into it.
///
/// The class is kept for two reasons:
///   1. it is the generator input for the M10 seed block, and
///   2. <see cref="SharbatlyQMS.Web.Services.CodeDescriptionDirectory"/> falls
///      back to it when a code has no DB row — so the list pages keep showing
///      names in the window between a binary deploy and the migration, and if
///      an admin ever deletes a row by mistake.
///
/// Do NOT add new codes here; add them in the admin page. Views must go
/// through ICodeDescriptionDirectory, never this class directly.
/// </summary>
public static class SapPlantDirectorySeed
{
    public sealed record Plant(string Code, string Name);
    public sealed record StorageLocation(string PlantCode, string Code, string Name);

    /// <summary>The 12 customer-facing plants. Codes that appear in
    /// <see cref="StorageLocations"/> but not here (e.g. SAP system
    /// defaults "0001", "0003", "DB02", "DB03", "RD02") are intentionally
    /// excluded; they should not surface as QC destinations.</summary>
    public static readonly IReadOnlyList<Plant> Plants = new Plant[]
    {
        new("AH01", "Al Hasa"),
        new("BH01", "Bahrain-Manama"),
        new("BU01", "Buraidah"),
        new("DB01", "UAE Main Site"),
        new("DM01", "Dammam"),
        new("HO01", "Head Office"),
        new("JD01", "Jeddah"),
        new("KH01", "Khamis Mushayt"),
        new("MD01", "Medinah"),
        new("MK01", "Makkah"),
        new("RD01", "Riyadh"),
        new("TB01", "Tabuk"),
    };

    public static readonly IReadOnlyList<StorageLocation> StorageLocations = new StorageLocation[]
    {
        // ---- SAP system plants (not in the QC plant master) ----
        new("0001", "0001", "Lager 0001"),
        new("0001", "0088", "Lager 0088 (WM)"),
        new("0001", "0100", "Lagerort WM&HU"),
        new("0001", "0200", "SCM-EWM"),
        new("0003", "0001", "Lager 0001"),
        new("0003", "0088", "Lager 0088 (WM)"),

        // ---- Al Hasa (AH01) ----
        new("AH01", "AHAM", "Hasa AdvMaterial"),
        new("AH01", "AHAU", "Hasa Auction"),
        new("AH01", "AHCS", "Hasa cold stores"),
        new("AH01", "AHDS", "Hasa Destraction"),
        new("AH01", "AHFD", "FDD Store Ahsa"),
        new("AH01", "AHHD", "AlHasa Home Del"),
        new("AH01", "AHTD", "Hasa Maintenance"),
        new("AH01", "MA01", "Montana Hasa 01"),
        new("AH01", "MA02", "Montana Hasa 02"),
        new("AH01", "MTAH", "MONTANA Store Ah"),
        new("AH01", "VA01", "VAN Hasa 01"),
        new("AH01", "VA02", "VAN Hasa 02"),
        new("AH01", "VA03", "VAN Hasa 03"),
        new("AH01", "VA04", "VAN Hasa 04"),
        new("AH01", "VA05", "VAN Hasa 05"),
        new("AH01", "VA06", "VAN Hasa 06"),
        new("AH01", "VA07", "VAN Hasa 07"),
        new("AH01", "VA08", "VAN Hasa 08"),
        new("AH01", "VA09", "VAN Hasa 09"),
        new("AH01", "VA10", "VAN Hasa 10"),
        new("AH01", "VA11", "VAN Hasa 11"),

        // ---- Bahrain (BH01) ----
        new("BH01", "BHFD", "FDD Store Manama"),
        new("BH01", "BHHD", "Bahrain Home del"),
        new("BH01", "M49G", "Shop No 249G"),
        new("BH01", "M49W", "Shop No 249W"),
        new("BH01", "MA04", "BH Shop LB04"),
        new("BH01", "MA05", "BH Shop LB05"),
        new("BH01", "MA06", "BH Shop LB06"),
        new("BH01", "MA08", "BH Shop LB08"),
        new("BH01", "MA16", "BH Shop LB16"),
        new("BH01", "MA17", "BH Shop LB17"),
        new("BH01", "MA35", "Shop No 35"),
        new("BH01", "MA79", "Shop No 79"),
        new("BH01", "MA83", "Shop No 83"),
        new("BH01", "MACA", "BH Catering-Smkt"),
        new("BH01", "MACM", "Manama Cnt Mrkt"),
        new("BH01", "MACS", "BH Main CS"),
        new("BH01", "MACT", "TRAFCO COLD STOR"),
        new("BH01", "MAFF", "Bahrain fresh fr"),
        new("BH01", "MAH1", "Halaga  No 01"),
        new("BH01", "MAH2", "Halaga No 02"),
        new("BH01", "MAH3", "Halaga No 03"),
        new("BH01", "MAL2", "BH LB2"),
        new("BH01", "MAL3", "BH LB3"),
        new("BH01", "MALM", "Packing line Mat"),
        new("BH01", "MAPL", "BH Packing Line"),
        new("BH01", "MAPT", "BH01 Tran Pack L"),
        new("BH01", "MASM", "BH Smkt kg"),
        new("BH01", "MASS", "cold store sales"),
        new("BH01", "MAVL", "Velocity Logisti"),
        new("BH01", "MAWW", "Warehouse World"),
        new("BH01", "MHC1", "Halaga Cons 01"),
        new("BH01", "MHC2", "Halaga Cons 02"),
        new("BH01", "MHC3", "Halaga Cons 03"),
        new("BH01", "MTBH", "MONTA Store Mana"),
        new("BH01", "VB55", "VAN Bahrain55"),
        new("BH01", "VB56", "VAN Bahrain56"),
        new("BH01", "VH01", "VAN Bahrain 01"),
        new("BH01", "VH02", "VAN Bahrain 02"),
        new("BH01", "VH03", "VAN Bahrain 03"),
        new("BH01", "VH04", "VAN Bahrain 04"),
        new("BH01", "VH05", "VAN Bahrain 05"),
        new("BH01", "VH06", "VAN Bahrain 06"),
        new("BH01", "VH07", "VAN Bahrain 07"),

        // ---- Buraidah (BU01) ----
        new("BU01", "BUAM", "Buraidh Advertis"),
        new("BU01", "BUAU", "Buraidh Auction"),
        new("BU01", "BUCS", "Buraidah Coldstr"),
        new("BU01", "BUDS", "Buraidh Destruca"),
        new("BU01", "BUFD", "FDD Store Buraid"),
        new("BU01", "BUHD", "Buraidh Home Del"),
        new("BU01", "BUTD", "Bur Main warehou"),
        new("BU01", "MB01", "Montana Burad 01"),
        new("BU01", "MB02", "Montana Burad 02"),
        new("BU01", "MTBU", "MONTANA Store Bu"),
        new("BU01", "VB01", "VAN Buraidh 01"),
        new("BU01", "VB02", "VAN Buraidh 02"),
        new("BU01", "VB03", "VAN Buraidh 03"),
        new("BU01", "VB04", "VAN Buraidh 04"),
        new("BU01", "VB05", "VAN Buraidh 05"),
        new("BU01", "VB06", "VAN Buraidh 06"),
        new("BU01", "VB07", "VAN Buraidh 07"),
        new("BU01", "VB08", "VAN Buraidh 08"),
        new("BU01", "VB09", "VAN Buraidh 09"),

        // ---- UAE / Dubai (DB01) ----
        new("DB01", "DBCS", "UAE Main ColdStr"),
        new("DB01", "DBDS", "Dubai Destructio"),
        new("DB01", "DBFD", "FDD Store Dubai"),
        new("DB01", "MTDB", "MONTANA Store Du"),
        new("DB01", "VU51", "VAN UAE 51"),
        new("DB01", "VU52", "VAN UAE 52"),
        new("DB01", "VU53", "VAN UAE 53"),
        new("DB01", "VU54", "VAN UAE 54"),
        new("DB01", "VU55", "VAN UAE 55"),
        new("DB01", "VU56", "VAN UAE 56"),
        new("DB01", "VU61", "VAN UAE 61"),
        new("DB01", "VU62", "VAN UAE 62"),
        new("DB01", "VU63", "VAN UAE 63"),
        new("DB01", "VU64", "VAN UAE 64"),
        new("DB01", "VU71", "VAN UAE 71"),
        new("DB01", "VU72", "VAN UAE 72"),
        new("DB01", "VU73", "VAN UAE 73"),
        new("DB01", "VU74", "VAN UAE 74"),

        // ---- SAP system plants in UAE region ----
        new("DB02", "0001", "Lager 0001"),
        new("DB02", "0088", "Lager 0088 (WM)"),
        new("DB02", "0100", "Lagerort WM&HU"),
        new("DB02", "0200", "SCM-EWM"),
        new("DB03", "0001", "Lager 0001"),
        new("DB03", "0088", "Lager 0088 (WM)"),
        new("DB03", "0100", "Lagerort WM&HU"),
        new("DB03", "0200", "SCM-EWM"),
        new("DB03", "DBRE", "Sharjah Rented-1"),

        // ---- Dammam (DM01) ----
        new("DM01", "DHDD", "DM Home DES"),
        new("DM01", "DMAM", "DAM Adv Material"),
        new("DM01", "DMCS", "DAM Main CS"),
        new("DM01", "DMDS", "DAM Dest WH"),
        new("DM01", "DMDT", "DM01 Tran E-com"),
        new("DM01", "DMFD", "FDD Store Dammam"),
        new("DM01", "DMHD", "E-Comm Home Dlvr"),
        new("DM01", "DMPL", "DAM Packing Line"),
        new("DM01", "DMPT", "DM01 Tran Pack L"),
        new("DM01", "DMTD", "Dammam Maintenan"),
        new("DM01", "DMWS", "Dammam Workshop"),
        new("DM01", "MD01", "Montana Damma 01"),
        new("DM01", "MD02", "Montana Damma 02"),
        new("DM01", "MD03", "Montana Damma 03"),
        new("DM01", "MD04", "Montana Damma 04"),
        new("DM01", "MD05", "Montana Damma 05"),
        new("DM01", "MD06", "Montana Damma 06"),
        new("DM01", "MD07", "Montana Damma 07"),
        new("DM01", "MD08", "Montana Damma 08"),
        new("DM01", "MD09", "Montana Damma 09"),
        new("DM01", "MD10", "Montana Damma 10"),
        new("DM01", "MD11", "Montana 11"),
        new("DM01", "MD12", "Montana 12"),
        new("DM01", "MD13", "Montana 13"),
        new("DM01", "MD14", "Montana 14"),
        new("DM01", "MD15", "Montana 15"),
        new("DM01", "MTDM", "MONTANA Store Da"),
        new("DM01", "VD01", "VAN Dammam 01"),
        new("DM01", "VD02", "VAN Dammam 02"),
        new("DM01", "VD03", "VAN Dammam 03"),
        new("DM01", "VD04", "VAN Dammam 04"),
        new("DM01", "VD05", "VAN Dammam 05"),
        new("DM01", "VD06", "VAN Dammam 06"),
        new("DM01", "VD07", "VAN Dammam 07"),
        new("DM01", "VD08", "VAN Dammam 08"),
        new("DM01", "VD09", "VAN Dammam 09"),
        new("DM01", "VD10", "VAN Dammam 10"),
        new("DM01", "VD11", "VAN Dammam 11"),
        new("DM01", "VD12", "VAN Dammam 12"),
        new("DM01", "VD13", "VAN Dammam 13"),
        new("DM01", "VD14", "VAN Dammam 14"),
        new("DM01", "VD15", "VAN Dammam 15"),
        new("DM01", "VD16", "VAN Dammam 16"),
        new("DM01", "VD17", "VAN Dammam 17"),
        new("DM01", "VD18", "VAN Dammam 18"),
        new("DM01", "VD19", "VAN Dammam 19"),
        new("DM01", "VD20", "VAN Dammam 20"),
        new("DM01", "VD21", "VAN Damam 21"),

        // ---- Head Office (HO01) ----
        new("HO01", "AHAU", "ALAHSA AUCTION"),
        new("HO01", "BHAU", "BAHRAIN AUCTION"),
        new("HO01", "BUAU", "BURAIDH AUCTION"),
        new("HO01", "DMAU", "DAMMAM AUCTION"),
        new("HO01", "HOBA", "Bahrain Airport"),
        new("HO01", "HOBS", "Bahrain Seaport"),
        new("HO01", "HODA", "Dammam Airport"),
        new("HO01", "HODP", "Dammam Seaport"),
        new("HO01", "HODS", "HeadOffice Destr"),
        new("HO01", "HOJA", "Jeddah Airport"),
        new("HO01", "HOJS", "Jeddah Seaport"),
        new("HO01", "HOKA", "KING ABD Seaport"),
        new("HO01", "HOKS", "Kuwait Shuwaikh"),
        new("HO01", "HOLS", "Head Office"),
        new("HO01", "HORA", "Riyadh Airport"),
        new("HO01", "HOUA", "Dubai Airport"),
        new("HO01", "HOUS", "Dubai Seaport"),
        new("HO01", "JDAU", "JEDDAH AUCTION"),
        new("HO01", "KHAU", "KHAMIS AUCTION"),
        new("HO01", "MDAU", "MADINH AUCTION"),
        new("HO01", "MKAU", "MAKKAH AUCTION"),
        new("HO01", "RDAU", "RIYADH AUCTION"),
        new("HO01", "TBAU", "TABUK AUCTION"),

        // ---- Jeddah (JD01) ----
        new("JD01", "BA22", "IT Store"),
        new("JD01", "BB21", "Old Inv Archv St"),
        new("JD01", "BC11", "ATCL Archive"),
        new("JD01", "BC12", "Tech Stationery"),
        new("JD01", "BE04", "Electrical Store"),
        new("JD01", "BE05", "Advertising Stor"),
        new("JD01", "BE06", "VIP Furniture St"),
        new("JD01", "BE07", "Safety Store"),
        new("JD01", "BE08", "Oil Store"),
        new("JD01", "BE09", "ETY-GEN Store"),
        new("JD01", "BE10", "Light Store"),
        new("JD01", "BF13", "Cntrl rom spr pr"),
        new("JD01", "BG01", "Workshop Main St"),
        new("JD01", "BG15", "Uniform Store"),
        new("JD01", "BH02", "Mis Palt Yrd Str"),
        new("JD01", "BH03", "Old Eq & Spr prt"),
        new("JD01", "BI14", "Ecom Pack stor"),
        new("JD01", "BM16", "VIP Garage Store"),
        new("JD01", "BO20", "Stat,Cater&Clean"),
        new("JD01", "BR17", "Arch old Doc Str"),
        new("JD01", "BR18", "Archive Store"),
        new("JD01", "BR19", "Scrp IT Elec Dev"),
        new("JD01", "BY23", "Pack line Spr pt"),
        new("JD01", "JD",   "JEDDAH"),
        new("JD01", "JDA1", "Panda Andalous"),
        new("JD01", "JDAB", "Panda Al Birr"),
        new("JD01", "JDAL", "Al Ameerah"),
        new("JD01", "JDAM", "JD Adv Matr. WH"),
        new("JD01", "JDAQ", "Al Qarni"),
        new("JD01", "JDAR", "Danube-Arbaeen"),
        new("JD01", "JDAS", "Panda AlSamir"),
        new("JD01", "JDAW", "Panda-248  Amwaj"),
        new("JD01", "JDB1", "BinDod Rusaifa23"),
        new("JD01", "JDB2", "BinDod Azizia-6"),
        new("JD01", "JDB3", "BinDodBinjll3-38"),
        new("JD01", "JDBA", "Bin Dawood Aya"),
        new("JD01", "JDBB", "BinDodBinjll2-37"),
        new("JD01", "JDBF", "in Dawood Al Fa"),
        new("JD01", "JDBH", "Bin Dawood Heera"),
        new("JD01", "JDBJ", "BinDod Binj-41"),
        new("JD01", "JDBK", "BinDod Kkiya-28"),
        new("JD01", "JDBM", "Bin Dawood Alham"),
        new("JD01", "JDBN", "Panda 249 Bani M"),
        new("JD01", "JDBR", "Bin Dawood Rab"),
        new("JD01", "JDBS", "Bin Dawood Sitte"),
        new("JD01", "JDBV", "BinDod vally-36"),
        new("JD01", "JDBW", "BinDod Awali-19"),
        new("JD01", "JDCA", "Cannibalized Par"),
        new("JD01", "JDCF", "JEDDAH CAFETERIA"),
        new("JD01", "JDCN", "JD Mntn contr-RM"),
        new("JD01", "JDCS", "JD Main Coldstor"),
        new("JD01", "JDDN", "Danube-North"),
        new("JD01", "JDDP", "Dnubplaza-168"),
        new("JD01", "JDDS", "JD Destruct WH"),
        new("JD01", "JDDT", "JD01 Tran E-com"),
        new("JD01", "JDF2", "Panda 237  Faisl"),
        new("JD01", "JDFD", "FDD Store Jeddah"),
        new("JD01", "JDFM", "Danube-FayfaMall"),
        new("JD01", "JDFR", "Danube JD Alfana"),
        new("JD01", "JDFS", "Panda Al Faisali"),
        new("JD01", "JDGT", "Panda 214  Ghirn"),
        new("JD01", "JDH1", "Jeddah Halaga 1"),
        new("JD01", "JDH2", "Jeddah Halaga 2"),
        new("JD01", "JDHA", "Danube-hmra Avnu"),
        new("JD01", "JDHD", "E-Comm Home Dlvr"),
        new("JD01", "JDHM", "Panda Al Hamad"),
        new("JD01", "JDHO", "Jeddah Headoffic"),
        new("JD01", "JDHR", "Danube-Hera MdRd"),
        new("JD01", "JDHT", "JD01 Tran Halaga"),
        new("JD01", "JDIT", "Tech WH  IT staf"),
        new("JD01", "JDJM", "Panda Jamea"),
        new("JD01", "JDJP", "Danube JD Park"),
        new("JD01", "JDJS", "Pnd Street-204"),
        new("JD01", "JDKE", "Pnd KAEC-223"),
        new("JD01", "JDKH", "Danube-Khalidia"),
        new("JD01", "JDKR", "PANDA-Gs Jedda"),
        new("JD01", "JDMA", "Panda Mall of Ar"),
        new("JD01", "JDMF", "Panda 240 Mishri"),
        new("JD01", "JDMM", "Pnd Mall-20010"),
        new("JD01", "JDMS", "PANDA-Mutib"),
        new("JD01", "JDMU", "Panda 20001 Murj"),
        new("JD01", "JDMW", "JD Mntain WH"),
        new("JD01", "JDMY", "DnubMayYard-187"),
        new("JD01", "JDND", "Danube-Al Nahd"),
        new("JD01", "JDNG", "Danube-NorthGate"),
        new("JD01", "JDNO", "PANDA-North"),
        new("JD01", "JDNZ", "Panda 257 Nuzha"),
        new("JD01", "JDOB", "Jeddah Obhor"),
        new("JD01", "JDP1", "JD Pickup point"),
        new("JD01", "JDPA", "Panda Almanar"),
        new("JD01", "JDPB", "Pnd Batha MC-239"),
        new("JD01", "JDPK", "Pnd Kakiya-20002"),
        new("JD01", "JDPL", "JD Packing Line"),
        new("JD01", "JDPT", "JD01 Tran Pack L"),
        new("JD01", "JDPW", "PndAwali-20011"),
        new("JD01", "JDPZ", "Panda 210 Waziri"),
        new("JD01", "JDRA", "Danube-RwdahAvnu"),
        new("JD01", "JDRC", "Jeddah Rented CS"),
        new("JD01", "JDRD", "Panda AlRiyadh"),
        new("JD01", "JDRN", "Panda Al Rayaan"),
        new("JD01", "JDRP", "Reconditioned Pa"),
        new("JD01", "JDRR", "PANDA-Ar Raw"),
        new("JD01", "JDRS", "Danube-Red Sea M"),
        new("JD01", "JDRU", "Panda Al-Rohaily"),
        new("JD01", "JDRW", "JD Rented Wareho"),
        new("JD01", "JDS2", "Panda 201 Safa"),
        new("JD01", "JDSA", "Panda Al Salam"),
        new("JD01", "JDSH", "Panda Safa 205"),
        new("JD01", "JDSL", "PANDA-Sari"),
        new("JD01", "JDSM", "Panda 208 Sharay"),
        new("JD01", "JDSP", "Main Spare Parts"),
        new("JD01", "JDSS", "Danube Salamah 1"),
        new("JD01", "JDST", "Main Statationar"),
        new("JD01", "JDSU", "Panda 250 Ameer"),
        new("JD01", "JDT1", "Danube-Tahlia 1"),
        new("JD01", "JDT2", "Danube-Tahlia 2"),
        new("JD01", "JDTD", "Technical WH"),
        new("JD01", "JDTM", "Dnub Mall-162"),
        new("JD01", "JDTP", "Dnub Park-180"),
        new("JD01", "JDTV", "DnubVillage-170"),
        new("JD01", "JDUJ", "Panda Ubar Aljun"),
        new("JD01", "JDUM", "Panda Umrah AlJa"),
        new("JD01", "JDVL", "Danube-Village"),
        new("JD01", "JDWC", "Tech WH Contract"),
        new("JD01", "JDWS", "JD01 Workshop"),
        new("JD01", "JHDD", "JD Home DES"),
        new("JD01", "MJ01", "Montana Jedda 01"),
        new("JD01", "MJ02", "Montana Jedda 02"),
        new("JD01", "MJ03", "Montana Jedda 03"),
        new("JD01", "MJ04", "Montana Jedda 04"),
        new("JD01", "MJ05", "Montana Jedda 05"),
        new("JD01", "MJ06", "Montana Jedda 06"),
        new("JD01", "MJ07", "Montana Jedda 07"),
        new("JD01", "MJ08", "Montana Jedda 08"),
        new("JD01", "MJ09", "Montana Jedda 09"),
        new("JD01", "MJ10", "Montana Jedda 10"),
        new("JD01", "MJ11", "Montana Jedda 11"),
        new("JD01", "MJ12", "Montana Jedda 12"),
        new("JD01", "MJ13", "Montana Jedda 13"),
        new("JD01", "MJ14", "Montana Jedda 14"),
        new("JD01", "MJ15", "Montana Jedda 15"),
        new("JD01", "MJ16", "Montana Jedda 16"),
        new("JD01", "MJ17", "Montana Jedda 17"),
        new("JD01", "MJ18", "Montana Jedda 18"),
        new("JD01", "MJ19", "Montana Jedda 19"),
        new("JD01", "MJ20", "Montana Jedda 20"),
        new("JD01", "MJ21", "Montana Jedda 21"),
        new("JD01", "MJ22", "Montana Jedda 22"),
        new("JD01", "MJ23", "Montana Jedda 23"),
        new("JD01", "MJ24", "Montana Jedda 24"),
        new("JD01", "MJ25", "Montana Jedda 25"),
        new("JD01", "MJ26", "Montana 26"),
        new("JD01", "MJ27", "Montana 27"),
        new("JD01", "MJ28", "Montana 28"),
        new("JD01", "MJ29", "Montana 29"),
        new("JD01", "MJ30", "Montana 30"),
        new("JD01", "MTJD", "MONTANA Store Je"),
        new("JD01", "VJ01", "VAN Jeddah 01"),
        new("JD01", "VJ02", "VAN Jeddah 02"),
        new("JD01", "VJ03", "VAN Jeddah 03"),
        new("JD01", "VJ04", "VAN Jeddah 04"),
        new("JD01", "VJ05", "VAN Jeddah 05"),
        new("JD01", "VJ06", "VAN Jeddah 06"),
        new("JD01", "VJ07", "VAN Jeddah 07"),
        new("JD01", "VJ08", "VAN Jeddah 08"),
        new("JD01", "VJ09", "VAN Jeddah 09"),
        new("JD01", "VJ10", "VAN Jeddah 10"),
        new("JD01", "VJ11", "VAN Jeddah 11"),
        new("JD01", "VJ12", "VAN Jeddah 12"),
        new("JD01", "VJ13", "VAN Jeddah 13"),
        new("JD01", "VJ14", "VAN Jeddah 14"),
        new("JD01", "VJ15", "VAN Jeddah 15"),
        new("JD01", "VJ16", "VAN Jeddah 16"),
        new("JD01", "VJ17", "VAN Jeddah 17"),
        new("JD01", "VJ18", "VAN Jeddah 18"),
        new("JD01", "VJ19", "VAN Jeddah 19"),
        new("JD01", "VJ20", "VAN Jeddah 20"),
        new("JD01", "VJ21", "VAN Jeddah 21"),
        new("JD01", "VJ22", "VAN Jeddah 22"),
        new("JD01", "VJ23", "VAN Jeddah 23"),
        new("JD01", "VJ24", "VAN Jeddah 24"),
        new("JD01", "Y24",  "Tire Store"),
        new("JD01", "Y25",  "Miscellaneous St"),
        new("JD01", "Y26",  "Miscellaneous St"),
        new("JD01", "Y27",  "Uniform Store 2"),
        new("JD01", "Y28",  "Vehicle Old Spar"),
        new("JD01", "Y29",  "Open Storage"),

        // ---- Khamis Mushayt (KH01) ----
        new("KH01", "KHA1", "Pnd Rd-70006"),
        new("KH01", "KHAM", "Khamis Advertisi"),
        new("KH01", "KHAR", "Danube AlArin"),
        new("KH01", "KHBM", "Pnd Mall-707"),
        new("KH01", "KHCS", "Kh Main CS"),
        new("KH01", "KHDS", "Khamis Destructi"),
        new("KH01", "KHFD", "FDD Store Khamis"),
        new("KH01", "KHHD", "Khamis Home Del"),
        new("KH01", "KHHG", "Khamis Halaga"),
        new("KH01", "KHHT", "KH01 Tran Halaga"),
        new("KH01", "KHMW", "KHAMIS Mntain WH"),
        new("KH01", "KHNA", "Pnd Airprt-70007"),
        new("KH01", "KHNZ", "Danube Nuzha"),
        new("KH01", "KHSH", "Danube Shati"),
        new("KH01", "KHTD", "Khamis Maintenan"),
        new("KH01", "KHUS", "Danube Umsarar"),
        new("KH01", "MK01", "Montana Khami 01"),
        new("KH01", "MK02", "Montana Khami 02"),
        new("KH01", "MTKH", "MONTANA Store Kh"),
        new("KH01", "VK01", "VAN Khamis 01"),
        new("KH01", "VK02", "VAN Khamis 02"),
        new("KH01", "VK03", "VAN Khamis 03"),
        new("KH01", "VK04", "VAN Khamis 04"),
        new("KH01", "VK05", "VAN Khamis 05"),
        new("KH01", "VK06", "VAN Khamis 06"),
        new("KH01", "VK07", "VAN Khamis 07"),
        new("KH01", "VK08", "VAN Khamis 08"),
        new("KH01", "VK09", "VAN Khamis 09"),
        new("KH01", "VK10", "VAN Khamis 10"),
        new("KH01", "VK11", "VAN Khamis 11"),
        new("KH01", "VK12", "VAN Khamis 12"),
        new("KH01", "VK13", "VAN Khamis 13"),
        new("KH01", "VK14", "VAN Khamis 14"),
        new("KH01", "VK15", "VAN Khamis 15"),
        new("KH01", "VK16", "VAN Khamis 16"),
        new("KH01", "VK17", "VAN Khamis 17"),
        new("KH01", "VK18", "VAN Khamis 18"),

        // ---- Medinah (MD01) ----
        new("MD01", "MDA1", "Pnd Mall-50001"),
        new("MD01", "MDAM", "Madinah Advertis"),
        new("MD01", "MDCS", "MD Main CS"),
        new("MD01", "MDDS", "Madinah Destruct"),
        new("MD01", "MDFD", "FDD Store Madina"),
        new("MD01", "MDHA", "Medinah Halagah"),
        new("MD01", "MDHD", "Madinah Home Del"),
        new("MD01", "MDHO", "Madinah Headoffi"),
        new("MD01", "MDHT", "MD01 Tran Halaga"),
        new("MD01", "MDMW", "MD Mntain WH"),
        new("MD01", "MDNM", "Pnd Mall-50003"),
        new("MD01", "MDSA", "Danube-Sultana"),
        new("MD01", "MDTD", "Madinah Maintena"),
        new("MD01", "MM01", "Montana Madin 01"),
        new("MD01", "MM02", "Montana Madin 02"),
        new("MD01", "MM03", "Montana Madia 03"),
        new("MD01", "MM04", "Montana Madia 04"),
        new("MD01", "MM05", "Montana Madia 05"),
        new("MD01", "MTMD", "MONTA Store Madi"),
        new("MD01", "VN01", "VAN Madinah 01"),
        new("MD01", "VN02", "VAN Madinah 02"),
        new("MD01", "VN03", "VAN Madinah 03"),
        new("MD01", "VN04", "VAN Madinah 04"),
        new("MD01", "VN05", "VAN Madinah 05"),
        new("MD01", "VN06", "VAN Madinah 06"),
        new("MD01", "VN07", "VAN Madinah 07"),
        new("MD01", "VN08", "VAN Madinah 08"),
        new("MD01", "VN09", "VAN Madinah 09"),

        // ---- Makkah (MK01) ----
        new("MK01", "MKAM", "Makkah Advertisi"),
        new("MK01", "MKCS", "MK Main CS"),
        new("MK01", "MKDS", "Makkah Destruct"),
        new("MK01", "MKFD", "FDD Store Makkah"),
        new("MK01", "MKTD", "Makkah Maintenan"),
        new("MK01", "MTMK", "MONTANA Store Ma"),
        new("MK01", "VM01", "VAN Makkah 01"),
        new("MK01", "VM02", "VAN Makkah 02"),
        new("MK01", "VM03", "VAN Makkah 03"),
        new("MK01", "VM04", "VAN Makkah 04"),
        new("MK01", "VM05", "VAN Makkah 05"),
        new("MK01", "VM06", "VAN Makkah 06"),
        new("MK01", "VM07", "VAN Makkah 07"),
        new("MK01", "VM08", "VAN Makkah 08"),
        new("MK01", "VM09", "VAN Makkah 09"),

        // ---- Riyadh (RD01) ----
        new("RD01", "MR01", "Montana Riyad 01"),
        new("RD01", "MR02", "Montana Riyad 02"),
        new("RD01", "MR03", "Montana Riyad 03"),
        new("RD01", "MR04", "Montana Riyad 04"),
        new("RD01", "MR05", "Montana Riyad 05"),
        new("RD01", "MR06", "Montana Riyad 06"),
        new("RD01", "MR07", "Montana Riyad 07"),
        new("RD01", "MR08", "Montana Riyad 08"),
        new("RD01", "MR09", "Montana Riyad 09"),
        new("RD01", "MR10", "Montana Riyad 10"),
        new("RD01", "MR11", "Montana Riyad 11"),
        new("RD01", "MR12", "Montana Riyad 12"),
        new("RD01", "MR13", "Montana Riyad 13"),
        new("RD01", "MR14", "Montana Riyad 14"),
        new("RD01", "MR15", "Montana Riyad 15"),
        new("RD01", "MR16", "Montana Riyad 16"),
        new("RD01", "MR17", "Montana Riyad 17"),
        new("RD01", "MR18", "Montana Riyad 18"),
        new("RD01", "MR19", "Montana Riyad 19"),
        new("RD01", "MR20", "Montana Riyad 20"),
        new("RD01", "MTRD", "MONTANA Store Ri"),
        new("RD01", "RAZ2", "RD Azizia Sales2"),
        new("RD01", "RD1T", "RD01 Tran  Aziz1"),
        new("RD01", "RD2T", "RD01 Tran  Aziz2"),
        new("RD01", "RDAB", "Panda RD Abubkar"),
        new("RD01", "RDAC", "Labor Accomodati"),
        new("RD01", "RDAM", "RD Adv Material"),
        new("RD01", "RDAP", "Panda 100 Awal P"),
        new("RD01", "RDAZ", "Panda Alaliah Pl"),
        new("RD01", "RDCS", "RD Main CS"),
        new("RD01", "RDDS", "Riyadh Dest WH"),
        new("RD01", "RDFD", "FDD Store Riyadh"),
        new("RD01", "RDGM", "Panda Riyadh Gal"),
        new("RD01", "RDHD", "E-Comm Home Dlvr"),
        new("RD01", "RDIA", "Riyadh Cold stor"),
        new("RD01", "RDLW", "Logistic service"),
        new("RD01", "RDMT", "Panda Al Maathar"),
        new("RD01", "RDMW", "RIYADH Mntain WH"),
        new("RD01", "RDOP", "Panda Al Orobah"),
        new("RD01", "RDPL", "RD PackingLine"),
        new("RD01", "RDPT", "RD01 Tran Pack L"),
        new("RD01", "RDRN", "Panda Rayyan"),
        new("RD01", "RDRW", "Rented Warehouse"),
        new("RD01", "RDTD", "Riyadh Maintenan"),
        new("RD01", "RDZ1", "RD Azizia Sales"),
        new("RD01", "RHDD", "RD Home DES"),
        new("RD01", "VR01", "VAN Riyadh 01"),
        new("RD01", "VR02", "VAN Riyadh 02"),
        new("RD01", "VR03", "VAN Riyadh 03"),
        new("RD01", "VR04", "VAN Riyadh 04"),
        new("RD01", "VR05", "VAN Riyadh 05"),
        new("RD01", "VR06", "VAN Riyadh 06"),
        new("RD01", "VR07", "VAN Riyadh 07"),
        new("RD01", "VR08", "VAN Riyadh 08"),
        new("RD01", "VR09", "VAN Riyadh 09"),
        new("RD01", "VR10", "VAN Riyadh 10"),
        new("RD01", "VR11", "VAN Riyadh 11"),
        new("RD01", "VR12", "VAN Riyadh 12"),
        new("RD01", "VR13", "VAN Riyadh 13"),
        new("RD01", "VR14", "VAN Riyadh 14"),
        new("RD01", "VR15", "VAN Riyadh 15"),
        new("RD01", "VR16", "VAN Riyadh 16"),
        new("RD01", "VR17", "VAN Riyadh 17"),
        new("RD01", "VR18", "VAN Riyadh 18"),
        new("RD01", "VR19", "VAN Riyadh 19"),
        new("RD01", "VR20", "VAN Riyadh 20"),
        new("RD01", "VR21", "VAN Riyadh 21"),
        new("RD01", "VR22", "VAN Riyadh 22"),
        new("RD01", "VR23", "VAN Riyadh 23"),
        new("RD01", "VR24", "VAN Riyadh 24"),
        new("RD01", "VR25", "VAN Riyadh 25"),
        new("RD01", "VR26", "VAN Riyadh 25"),

        // ---- SAP system plants in Riyadh region ----
        new("RD02", "0001", "Lager 0001"),
        new("RD02", "0088", "Lager 0088 (WM)"),
        new("RD02", "0100", "Lagerort WM&HU"),
        new("RD02", "0200", "SCM-EWM"),
        new("RD02", "RDIA", "RD CS indus area"),
        new("RD02", "RDIL", "RD CS indust Lbr"),

        // ---- Tabuk (TB01) ----
        new("TB01", "MT01", "Montana Tabuk 01"),
        new("TB01", "MTTB", "MONTANA Store Ta"),
        new("TB01", "TBAM", "TB Adv Material"),
        new("TB01", "TBCS", "TB Main CS"),
        new("TB01", "TBDS", "Tabuk Destructio"),
        new("TB01", "TBFD", "FDD Store Tabouk"),
        new("TB01", "TBHA", "Tabuk Halaga"),
        new("TB01", "TBHD", "Tabuk Home Del"),
        new("TB01", "TBHT", "TB01 Tran Halaga"),
        new("TB01", "TBTD", "Tabuk Maintenanc"),
        new("TB01", "VT01", "VAN Tabuk 01"),
        new("TB01", "VT02", "VAN Tabuk 02"),
        new("TB01", "VT03", "VAN Tabuk 03"),
        new("TB01", "VT04", "VAN Tabuk 04"),
        new("TB01", "VT05", "VAN Tabuk 05"),
        new("TB01", "VT06", "VAN Tabuk 06"),
        new("TB01", "VT07", "VAN Tabuk 07"),
        new("TB01", "VT08", "VAN Tabuk 08"),
    };

    private static readonly IReadOnlyDictionary<string, string> _plantNames =
        Plants.ToDictionary(p => p.Code, p => p.Name, StringComparer.OrdinalIgnoreCase);

    private static readonly IReadOnlyDictionary<string, string> _storageNames =
        StorageLocations.ToDictionary(
            s => Key(s.PlantCode, s.Code),
            s => s.Name,
            StringComparer.OrdinalIgnoreCase);

    private static string Key(string plant, string code) => $"{plant}|{code}";

    /// <summary>Returns the friendly plant name, or null if the code is not in the master list.</summary>
    public static string? PlantName(string? code) =>
        !string.IsNullOrWhiteSpace(code) && _plantNames.TryGetValue(code, out var n) ? n : null;

    /// <summary>Returns the friendly storage-location name, or null if the (plant, code) pair is not in the master list.</summary>
    public static string? StorageLocationName(string? plant, string? code) =>
        !string.IsNullOrWhiteSpace(plant) && !string.IsNullOrWhiteSpace(code)
            && _storageNames.TryGetValue(Key(plant!, code!), out var n) ? n : null;

    /// <summary>Renders "CODE — Name" when the name is known, otherwise just the code.</summary>
    public static string PlantLabel(string? code) =>
        PlantName(code) is { } n ? $"{code} — {n}" : (code ?? "");

    /// <summary>Renders "CODE — Name" when the name is known, otherwise just the code.</summary>
    public static string StorageLocationLabel(string? plant, string? code) =>
        StorageLocationName(plant, code) is { } n ? $"{code} — {n}" : (code ?? "");
}
