-- ============================================================================
--  SharbatlyQMS on Sharbatly_MIS  -  M10  -  Code descriptions
-- ============================================================================
--  Friendly names for the raw SAP codes the UI used to print bare:
--     Plant            JD01 -> Jeddah
--     StorageLocation  (JD01) JDCS -> JD Main Coldstor
--     PoType           ZFAS -> Air Shipment
--
--  Storage-location codes repeat across plants, so parent_code carries the
--  owning plant. Plant and PoType rows leave it NULL; parent_key is the
--  persisted ISNULL() of it purely so the uniqueness constraint works.
--
--  This replaces the hard-coded Models/SapPlantDirectory.cs lookup. That file
--  stays in the binary as SapPlantDirectorySeed and remains the fallback when
--  a code has no row here, so the list pages keep rendering names during the
--  window between a binary deploy and this migration.
--
--  The Plant + StorageLocation seed below is GENERATED from that C# file
--  (scratchpad/gen-code-desc-seed.ps1) -- do not hand-edit rows; regenerate.
--  PoType has no SAP master table anywhere, so it is seeded from whatever
--  codes the container cache has actually seen, with description = code. That
--  gives the admin a worklist to type real names into, not a blank page.
--
--  Managed from Parameters > Code Descriptions (Manager/SiteAdmin).
--  Idempotent: safe to re-run.
-- ============================================================================

IF OBJECT_ID('qms.qms_code_description') IS NULL
BEGIN
    CREATE TABLE qms.qms_code_description (
        code_desc_id  INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_qms_code_description PRIMARY KEY,
        domain        VARCHAR(20)  NOT NULL,
        parent_code   VARCHAR(4)   NULL,
        parent_key    AS ISNULL(parent_code, '') PERSISTED,
        code          VARCHAR(10)  NOT NULL,
        description   NVARCHAR(80) NOT NULL,
        sort_order    INT          NOT NULL
            CONSTRAINT DF_qms_code_description_sort DEFAULT 500,
        is_active     BIT          NOT NULL
            CONSTRAINT DF_qms_code_description_active DEFAULT 1,
        updated_at    DATETIME2    NOT NULL
            CONSTRAINT DF_qms_code_description_upd DEFAULT SYSUTCDATETIME(),
        updated_by    NVARCHAR(100) NULL,
        CONSTRAINT CK_qms_code_description_domain
            CHECK (domain IN ('Plant','StorageLocation','PoType')),
        CONSTRAINT UQ_qms_code_description
            UNIQUE (domain, parent_key, code)
    );
END
GO

-- The app addresses the table by its bare name; mirror the M05 convention.
IF OBJECT_ID('dbo.qms_code_description') IS NULL
    CREATE SYNONYM dbo.qms_code_description FOR qms.qms_code_description;
GO

-- ---- Seed: plants (generated from Models/SapPlantDirectory.cs) ----
MERGE qms.qms_code_description AS t
USING (VALUES
-- First row casts NULL so the VALUES constructor can type the column
-- (every plant row is NULL, so SQL Server has nothing else to infer from).
('Plant', CAST(NULL AS VARCHAR(4)), 'AH01', N'Al Hasa'),
('Plant', NULL, 'BH01', N'Bahrain-Manama'),
('Plant', NULL, 'BU01', N'Buraidah'),
('Plant', NULL, 'DB01', N'UAE Main Site'),
('Plant', NULL, 'DM01', N'Dammam'),
('Plant', NULL, 'HO01', N'Head Office'),
('Plant', NULL, 'JD01', N'Jeddah'),
('Plant', NULL, 'KH01', N'Khamis Mushayt'),
('Plant', NULL, 'MD01', N'Medinah'),
('Plant', NULL, 'MK01', N'Makkah'),
('Plant', NULL, 'RD01', N'Riyadh'),
('Plant', NULL, 'TB01', N'Tabuk')
) AS s(domain, parent_code, code, description)
    ON  t.domain = s.domain
    AND ISNULL(t.parent_code,'') = ISNULL(s.parent_code,'')
    AND t.code = s.code
WHEN NOT MATCHED THEN
    INSERT (domain, parent_code, code, description, updated_by)
    VALUES (s.domain, s.parent_code, s.code, s.description, 'seed-M10');
GO

-- ---- Seed: storage locations 1-250 ----
MERGE qms.qms_code_description AS t
USING (VALUES
('StorageLocation', '0001', '0001', N'Lager 0001'),
('StorageLocation', '0001', '0088', N'Lager 0088 (WM)'),
('StorageLocation', '0001', '0100', N'Lagerort WM&HU'),
('StorageLocation', '0001', '0200', N'SCM-EWM'),
('StorageLocation', '0003', '0001', N'Lager 0001'),
('StorageLocation', '0003', '0088', N'Lager 0088 (WM)'),
('StorageLocation', 'AH01', 'AHAM', N'Hasa AdvMaterial'),
('StorageLocation', 'AH01', 'AHAU', N'Hasa Auction'),
('StorageLocation', 'AH01', 'AHCS', N'Hasa cold stores'),
('StorageLocation', 'AH01', 'AHDS', N'Hasa Destraction'),
('StorageLocation', 'AH01', 'AHFD', N'FDD Store Ahsa'),
('StorageLocation', 'AH01', 'AHHD', N'AlHasa Home Del'),
('StorageLocation', 'AH01', 'AHTD', N'Hasa Maintenance'),
('StorageLocation', 'AH01', 'MA01', N'Montana Hasa 01'),
('StorageLocation', 'AH01', 'MA02', N'Montana Hasa 02'),
('StorageLocation', 'AH01', 'MTAH', N'MONTANA Store Ah'),
('StorageLocation', 'AH01', 'VA01', N'VAN Hasa 01'),
('StorageLocation', 'AH01', 'VA02', N'VAN Hasa 02'),
('StorageLocation', 'AH01', 'VA03', N'VAN Hasa 03'),
('StorageLocation', 'AH01', 'VA04', N'VAN Hasa 04'),
('StorageLocation', 'AH01', 'VA05', N'VAN Hasa 05'),
('StorageLocation', 'AH01', 'VA06', N'VAN Hasa 06'),
('StorageLocation', 'AH01', 'VA07', N'VAN Hasa 07'),
('StorageLocation', 'AH01', 'VA08', N'VAN Hasa 08'),
('StorageLocation', 'AH01', 'VA09', N'VAN Hasa 09'),
('StorageLocation', 'AH01', 'VA10', N'VAN Hasa 10'),
('StorageLocation', 'AH01', 'VA11', N'VAN Hasa 11'),
('StorageLocation', 'BH01', 'BHFD', N'FDD Store Manama'),
('StorageLocation', 'BH01', 'BHHD', N'Bahrain Home del'),
('StorageLocation', 'BH01', 'M49G', N'Shop No 249G'),
('StorageLocation', 'BH01', 'M49W', N'Shop No 249W'),
('StorageLocation', 'BH01', 'MA04', N'BH Shop LB04'),
('StorageLocation', 'BH01', 'MA05', N'BH Shop LB05'),
('StorageLocation', 'BH01', 'MA06', N'BH Shop LB06'),
('StorageLocation', 'BH01', 'MA08', N'BH Shop LB08'),
('StorageLocation', 'BH01', 'MA16', N'BH Shop LB16'),
('StorageLocation', 'BH01', 'MA17', N'BH Shop LB17'),
('StorageLocation', 'BH01', 'MA35', N'Shop No 35'),
('StorageLocation', 'BH01', 'MA79', N'Shop No 79'),
('StorageLocation', 'BH01', 'MA83', N'Shop No 83'),
('StorageLocation', 'BH01', 'MACA', N'BH Catering-Smkt'),
('StorageLocation', 'BH01', 'MACM', N'Manama Cnt Mrkt'),
('StorageLocation', 'BH01', 'MACS', N'BH Main CS'),
('StorageLocation', 'BH01', 'MACT', N'TRAFCO COLD STOR'),
('StorageLocation', 'BH01', 'MAFF', N'Bahrain fresh fr'),
('StorageLocation', 'BH01', 'MAH1', N'Halaga  No 01'),
('StorageLocation', 'BH01', 'MAH2', N'Halaga No 02'),
('StorageLocation', 'BH01', 'MAH3', N'Halaga No 03'),
('StorageLocation', 'BH01', 'MAL2', N'BH LB2'),
('StorageLocation', 'BH01', 'MAL3', N'BH LB3'),
('StorageLocation', 'BH01', 'MALM', N'Packing line Mat'),
('StorageLocation', 'BH01', 'MAPL', N'BH Packing Line'),
('StorageLocation', 'BH01', 'MAPT', N'BH01 Tran Pack L'),
('StorageLocation', 'BH01', 'MASM', N'BH Smkt kg'),
('StorageLocation', 'BH01', 'MASS', N'cold store sales'),
('StorageLocation', 'BH01', 'MAVL', N'Velocity Logisti'),
('StorageLocation', 'BH01', 'MAWW', N'Warehouse World'),
('StorageLocation', 'BH01', 'MHC1', N'Halaga Cons 01'),
('StorageLocation', 'BH01', 'MHC2', N'Halaga Cons 02'),
('StorageLocation', 'BH01', 'MHC3', N'Halaga Cons 03'),
('StorageLocation', 'BH01', 'MTBH', N'MONTA Store Mana'),
('StorageLocation', 'BH01', 'VB55', N'VAN Bahrain55'),
('StorageLocation', 'BH01', 'VB56', N'VAN Bahrain56'),
('StorageLocation', 'BH01', 'VH01', N'VAN Bahrain 01'),
('StorageLocation', 'BH01', 'VH02', N'VAN Bahrain 02'),
('StorageLocation', 'BH01', 'VH03', N'VAN Bahrain 03'),
('StorageLocation', 'BH01', 'VH04', N'VAN Bahrain 04'),
('StorageLocation', 'BH01', 'VH05', N'VAN Bahrain 05'),
('StorageLocation', 'BH01', 'VH06', N'VAN Bahrain 06'),
('StorageLocation', 'BH01', 'VH07', N'VAN Bahrain 07'),
('StorageLocation', 'BU01', 'BUAM', N'Buraidh Advertis'),
('StorageLocation', 'BU01', 'BUAU', N'Buraidh Auction'),
('StorageLocation', 'BU01', 'BUCS', N'Buraidah Coldstr'),
('StorageLocation', 'BU01', 'BUDS', N'Buraidh Destruca'),
('StorageLocation', 'BU01', 'BUFD', N'FDD Store Buraid'),
('StorageLocation', 'BU01', 'BUHD', N'Buraidh Home Del'),
('StorageLocation', 'BU01', 'BUTD', N'Bur Main warehou'),
('StorageLocation', 'BU01', 'MB01', N'Montana Burad 01'),
('StorageLocation', 'BU01', 'MB02', N'Montana Burad 02'),
('StorageLocation', 'BU01', 'MTBU', N'MONTANA Store Bu'),
('StorageLocation', 'BU01', 'VB01', N'VAN Buraidh 01'),
('StorageLocation', 'BU01', 'VB02', N'VAN Buraidh 02'),
('StorageLocation', 'BU01', 'VB03', N'VAN Buraidh 03'),
('StorageLocation', 'BU01', 'VB04', N'VAN Buraidh 04'),
('StorageLocation', 'BU01', 'VB05', N'VAN Buraidh 05'),
('StorageLocation', 'BU01', 'VB06', N'VAN Buraidh 06'),
('StorageLocation', 'BU01', 'VB07', N'VAN Buraidh 07'),
('StorageLocation', 'BU01', 'VB08', N'VAN Buraidh 08'),
('StorageLocation', 'BU01', 'VB09', N'VAN Buraidh 09'),
('StorageLocation', 'DB01', 'DBCS', N'UAE Main ColdStr'),
('StorageLocation', 'DB01', 'DBDS', N'Dubai Destructio'),
('StorageLocation', 'DB01', 'DBFD', N'FDD Store Dubai'),
('StorageLocation', 'DB01', 'MTDB', N'MONTANA Store Du'),
('StorageLocation', 'DB01', 'VU51', N'VAN UAE 51'),
('StorageLocation', 'DB01', 'VU52', N'VAN UAE 52'),
('StorageLocation', 'DB01', 'VU53', N'VAN UAE 53'),
('StorageLocation', 'DB01', 'VU54', N'VAN UAE 54'),
('StorageLocation', 'DB01', 'VU55', N'VAN UAE 55'),
('StorageLocation', 'DB01', 'VU56', N'VAN UAE 56'),
('StorageLocation', 'DB01', 'VU61', N'VAN UAE 61'),
('StorageLocation', 'DB01', 'VU62', N'VAN UAE 62'),
('StorageLocation', 'DB01', 'VU63', N'VAN UAE 63'),
('StorageLocation', 'DB01', 'VU64', N'VAN UAE 64'),
('StorageLocation', 'DB01', 'VU71', N'VAN UAE 71'),
('StorageLocation', 'DB01', 'VU72', N'VAN UAE 72'),
('StorageLocation', 'DB01', 'VU73', N'VAN UAE 73'),
('StorageLocation', 'DB01', 'VU74', N'VAN UAE 74'),
('StorageLocation', 'DB02', '0001', N'Lager 0001'),
('StorageLocation', 'DB02', '0088', N'Lager 0088 (WM)'),
('StorageLocation', 'DB02', '0100', N'Lagerort WM&HU'),
('StorageLocation', 'DB02', '0200', N'SCM-EWM'),
('StorageLocation', 'DB03', '0001', N'Lager 0001'),
('StorageLocation', 'DB03', '0088', N'Lager 0088 (WM)'),
('StorageLocation', 'DB03', '0100', N'Lagerort WM&HU'),
('StorageLocation', 'DB03', '0200', N'SCM-EWM'),
('StorageLocation', 'DB03', 'DBRE', N'Sharjah Rented-1'),
('StorageLocation', 'DM01', 'DHDD', N'DM Home DES'),
('StorageLocation', 'DM01', 'DMAM', N'DAM Adv Material'),
('StorageLocation', 'DM01', 'DMCS', N'DAM Main CS'),
('StorageLocation', 'DM01', 'DMDS', N'DAM Dest WH'),
('StorageLocation', 'DM01', 'DMDT', N'DM01 Tran E-com'),
('StorageLocation', 'DM01', 'DMFD', N'FDD Store Dammam'),
('StorageLocation', 'DM01', 'DMHD', N'E-Comm Home Dlvr'),
('StorageLocation', 'DM01', 'DMPL', N'DAM Packing Line'),
('StorageLocation', 'DM01', 'DMPT', N'DM01 Tran Pack L'),
('StorageLocation', 'DM01', 'DMTD', N'Dammam Maintenan'),
('StorageLocation', 'DM01', 'DMWS', N'Dammam Workshop'),
('StorageLocation', 'DM01', 'MD01', N'Montana Damma 01'),
('StorageLocation', 'DM01', 'MD02', N'Montana Damma 02'),
('StorageLocation', 'DM01', 'MD03', N'Montana Damma 03'),
('StorageLocation', 'DM01', 'MD04', N'Montana Damma 04'),
('StorageLocation', 'DM01', 'MD05', N'Montana Damma 05'),
('StorageLocation', 'DM01', 'MD06', N'Montana Damma 06'),
('StorageLocation', 'DM01', 'MD07', N'Montana Damma 07'),
('StorageLocation', 'DM01', 'MD08', N'Montana Damma 08'),
('StorageLocation', 'DM01', 'MD09', N'Montana Damma 09'),
('StorageLocation', 'DM01', 'MD10', N'Montana Damma 10'),
('StorageLocation', 'DM01', 'MD11', N'Montana 11'),
('StorageLocation', 'DM01', 'MD12', N'Montana 12'),
('StorageLocation', 'DM01', 'MD13', N'Montana 13'),
('StorageLocation', 'DM01', 'MD14', N'Montana 14'),
('StorageLocation', 'DM01', 'MD15', N'Montana 15'),
('StorageLocation', 'DM01', 'MTDM', N'MONTANA Store Da'),
('StorageLocation', 'DM01', 'VD01', N'VAN Dammam 01'),
('StorageLocation', 'DM01', 'VD02', N'VAN Dammam 02'),
('StorageLocation', 'DM01', 'VD03', N'VAN Dammam 03'),
('StorageLocation', 'DM01', 'VD04', N'VAN Dammam 04'),
('StorageLocation', 'DM01', 'VD05', N'VAN Dammam 05'),
('StorageLocation', 'DM01', 'VD06', N'VAN Dammam 06'),
('StorageLocation', 'DM01', 'VD07', N'VAN Dammam 07'),
('StorageLocation', 'DM01', 'VD08', N'VAN Dammam 08'),
('StorageLocation', 'DM01', 'VD09', N'VAN Dammam 09'),
('StorageLocation', 'DM01', 'VD10', N'VAN Dammam 10'),
('StorageLocation', 'DM01', 'VD11', N'VAN Dammam 11'),
('StorageLocation', 'DM01', 'VD12', N'VAN Dammam 12'),
('StorageLocation', 'DM01', 'VD13', N'VAN Dammam 13'),
('StorageLocation', 'DM01', 'VD14', N'VAN Dammam 14'),
('StorageLocation', 'DM01', 'VD15', N'VAN Dammam 15'),
('StorageLocation', 'DM01', 'VD16', N'VAN Dammam 16'),
('StorageLocation', 'DM01', 'VD17', N'VAN Dammam 17'),
('StorageLocation', 'DM01', 'VD18', N'VAN Dammam 18'),
('StorageLocation', 'DM01', 'VD19', N'VAN Dammam 19'),
('StorageLocation', 'DM01', 'VD20', N'VAN Dammam 20'),
('StorageLocation', 'DM01', 'VD21', N'VAN Damam 21'),
('StorageLocation', 'HO01', 'AHAU', N'ALAHSA AUCTION'),
('StorageLocation', 'HO01', 'BHAU', N'BAHRAIN AUCTION'),
('StorageLocation', 'HO01', 'BUAU', N'BURAIDH AUCTION'),
('StorageLocation', 'HO01', 'DMAU', N'DAMMAM AUCTION'),
('StorageLocation', 'HO01', 'HOBA', N'Bahrain Airport'),
('StorageLocation', 'HO01', 'HOBS', N'Bahrain Seaport'),
('StorageLocation', 'HO01', 'HODA', N'Dammam Airport'),
('StorageLocation', 'HO01', 'HODP', N'Dammam Seaport'),
('StorageLocation', 'HO01', 'HODS', N'HeadOffice Destr'),
('StorageLocation', 'HO01', 'HOJA', N'Jeddah Airport'),
('StorageLocation', 'HO01', 'HOJS', N'Jeddah Seaport'),
('StorageLocation', 'HO01', 'HOKA', N'KING ABD Seaport'),
('StorageLocation', 'HO01', 'HOKS', N'Kuwait Shuwaikh'),
('StorageLocation', 'HO01', 'HOLS', N'Head Office'),
('StorageLocation', 'HO01', 'HORA', N'Riyadh Airport'),
('StorageLocation', 'HO01', 'HOUA', N'Dubai Airport'),
('StorageLocation', 'HO01', 'HOUS', N'Dubai Seaport'),
('StorageLocation', 'HO01', 'JDAU', N'JEDDAH AUCTION'),
('StorageLocation', 'HO01', 'KHAU', N'KHAMIS AUCTION'),
('StorageLocation', 'HO01', 'MDAU', N'MADINH AUCTION'),
('StorageLocation', 'HO01', 'MKAU', N'MAKKAH AUCTION'),
('StorageLocation', 'HO01', 'RDAU', N'RIYADH AUCTION'),
('StorageLocation', 'HO01', 'TBAU', N'TABUK AUCTION'),
('StorageLocation', 'JD01', 'BA22', N'IT Store'),
('StorageLocation', 'JD01', 'BB21', N'Old Inv Archv St'),
('StorageLocation', 'JD01', 'BC11', N'ATCL Archive'),
('StorageLocation', 'JD01', 'BC12', N'Tech Stationery'),
('StorageLocation', 'JD01', 'BE04', N'Electrical Store'),
('StorageLocation', 'JD01', 'BE05', N'Advertising Stor'),
('StorageLocation', 'JD01', 'BE06', N'VIP Furniture St'),
('StorageLocation', 'JD01', 'BE07', N'Safety Store'),
('StorageLocation', 'JD01', 'BE08', N'Oil Store'),
('StorageLocation', 'JD01', 'BE09', N'ETY-GEN Store'),
('StorageLocation', 'JD01', 'BE10', N'Light Store'),
('StorageLocation', 'JD01', 'BF13', N'Cntrl rom spr pr'),
('StorageLocation', 'JD01', 'BG01', N'Workshop Main St'),
('StorageLocation', 'JD01', 'BG15', N'Uniform Store'),
('StorageLocation', 'JD01', 'BH02', N'Mis Palt Yrd Str'),
('StorageLocation', 'JD01', 'BH03', N'Old Eq & Spr prt'),
('StorageLocation', 'JD01', 'BI14', N'Ecom Pack stor'),
('StorageLocation', 'JD01', 'BM16', N'VIP Garage Store'),
('StorageLocation', 'JD01', 'BO20', N'Stat,Cater&Clean'),
('StorageLocation', 'JD01', 'BR17', N'Arch old Doc Str'),
('StorageLocation', 'JD01', 'BR18', N'Archive Store'),
('StorageLocation', 'JD01', 'BR19', N'Scrp IT Elec Dev'),
('StorageLocation', 'JD01', 'BY23', N'Pack line Spr pt'),
('StorageLocation', 'JD01', 'JD', N'JEDDAH'),
('StorageLocation', 'JD01', 'JDA1', N'Panda Andalous'),
('StorageLocation', 'JD01', 'JDAB', N'Panda Al Birr'),
('StorageLocation', 'JD01', 'JDAL', N'Al Ameerah'),
('StorageLocation', 'JD01', 'JDAM', N'JD Adv Matr. WH'),
('StorageLocation', 'JD01', 'JDAQ', N'Al Qarni'),
('StorageLocation', 'JD01', 'JDAR', N'Danube-Arbaeen'),
('StorageLocation', 'JD01', 'JDAS', N'Panda AlSamir'),
('StorageLocation', 'JD01', 'JDAW', N'Panda-248  Amwaj'),
('StorageLocation', 'JD01', 'JDB1', N'BinDod Rusaifa23'),
('StorageLocation', 'JD01', 'JDB2', N'BinDod Azizia-6'),
('StorageLocation', 'JD01', 'JDB3', N'BinDodBinjll3-38'),
('StorageLocation', 'JD01', 'JDBA', N'Bin Dawood Aya'),
('StorageLocation', 'JD01', 'JDBB', N'BinDodBinjll2-37'),
('StorageLocation', 'JD01', 'JDBF', N'in Dawood Al Fa'),
('StorageLocation', 'JD01', 'JDBH', N'Bin Dawood Heera'),
('StorageLocation', 'JD01', 'JDBJ', N'BinDod Binj-41'),
('StorageLocation', 'JD01', 'JDBK', N'BinDod Kkiya-28'),
('StorageLocation', 'JD01', 'JDBM', N'Bin Dawood Alham'),
('StorageLocation', 'JD01', 'JDBN', N'Panda 249 Bani M'),
('StorageLocation', 'JD01', 'JDBR', N'Bin Dawood Rab'),
('StorageLocation', 'JD01', 'JDBS', N'Bin Dawood Sitte'),
('StorageLocation', 'JD01', 'JDBV', N'BinDod vally-36'),
('StorageLocation', 'JD01', 'JDBW', N'BinDod Awali-19'),
('StorageLocation', 'JD01', 'JDCA', N'Cannibalized Par'),
('StorageLocation', 'JD01', 'JDCF', N'JEDDAH CAFETERIA'),
('StorageLocation', 'JD01', 'JDCN', N'JD Mntn contr-RM'),
('StorageLocation', 'JD01', 'JDCS', N'JD Main Coldstor'),
('StorageLocation', 'JD01', 'JDDN', N'Danube-North'),
('StorageLocation', 'JD01', 'JDDP', N'Dnubplaza-168'),
('StorageLocation', 'JD01', 'JDDS', N'JD Destruct WH'),
('StorageLocation', 'JD01', 'JDDT', N'JD01 Tran E-com'),
('StorageLocation', 'JD01', 'JDF2', N'Panda 237  Faisl'),
('StorageLocation', 'JD01', 'JDFD', N'FDD Store Jeddah'),
('StorageLocation', 'JD01', 'JDFM', N'Danube-FayfaMall'),
('StorageLocation', 'JD01', 'JDFR', N'Danube JD Alfana'),
('StorageLocation', 'JD01', 'JDFS', N'Panda Al Faisali'),
('StorageLocation', 'JD01', 'JDGT', N'Panda 214  Ghirn'),
('StorageLocation', 'JD01', 'JDH1', N'Jeddah Halaga 1'),
('StorageLocation', 'JD01', 'JDH2', N'Jeddah Halaga 2')
) AS s(domain, parent_code, code, description)
    ON  t.domain = s.domain
    AND ISNULL(t.parent_code,'') = ISNULL(s.parent_code,'')
    AND t.code = s.code
WHEN NOT MATCHED THEN
    INSERT (domain, parent_code, code, description, updated_by)
    VALUES (s.domain, s.parent_code, s.code, s.description, 'seed-M10');
GO

-- ---- Seed: storage locations 251-500 ----
MERGE qms.qms_code_description AS t
USING (VALUES
('StorageLocation', 'JD01', 'JDHA', N'Danube-hmra Avnu'),
('StorageLocation', 'JD01', 'JDHD', N'E-Comm Home Dlvr'),
('StorageLocation', 'JD01', 'JDHM', N'Panda Al Hamad'),
('StorageLocation', 'JD01', 'JDHO', N'Jeddah Headoffic'),
('StorageLocation', 'JD01', 'JDHR', N'Danube-Hera MdRd'),
('StorageLocation', 'JD01', 'JDHT', N'JD01 Tran Halaga'),
('StorageLocation', 'JD01', 'JDIT', N'Tech WH  IT staf'),
('StorageLocation', 'JD01', 'JDJM', N'Panda Jamea'),
('StorageLocation', 'JD01', 'JDJP', N'Danube JD Park'),
('StorageLocation', 'JD01', 'JDJS', N'Pnd Street-204'),
('StorageLocation', 'JD01', 'JDKE', N'Pnd KAEC-223'),
('StorageLocation', 'JD01', 'JDKH', N'Danube-Khalidia'),
('StorageLocation', 'JD01', 'JDKR', N'PANDA-Gs Jedda'),
('StorageLocation', 'JD01', 'JDMA', N'Panda Mall of Ar'),
('StorageLocation', 'JD01', 'JDMF', N'Panda 240 Mishri'),
('StorageLocation', 'JD01', 'JDMM', N'Pnd Mall-20010'),
('StorageLocation', 'JD01', 'JDMS', N'PANDA-Mutib'),
('StorageLocation', 'JD01', 'JDMU', N'Panda 20001 Murj'),
('StorageLocation', 'JD01', 'JDMW', N'JD Mntain WH'),
('StorageLocation', 'JD01', 'JDMY', N'DnubMayYard-187'),
('StorageLocation', 'JD01', 'JDND', N'Danube-Al Nahd'),
('StorageLocation', 'JD01', 'JDNG', N'Danube-NorthGate'),
('StorageLocation', 'JD01', 'JDNO', N'PANDA-North'),
('StorageLocation', 'JD01', 'JDNZ', N'Panda 257 Nuzha'),
('StorageLocation', 'JD01', 'JDOB', N'Jeddah Obhor'),
('StorageLocation', 'JD01', 'JDP1', N'JD Pickup point'),
('StorageLocation', 'JD01', 'JDPA', N'Panda Almanar'),
('StorageLocation', 'JD01', 'JDPB', N'Pnd Batha MC-239'),
('StorageLocation', 'JD01', 'JDPK', N'Pnd Kakiya-20002'),
('StorageLocation', 'JD01', 'JDPL', N'JD Packing Line'),
('StorageLocation', 'JD01', 'JDPT', N'JD01 Tran Pack L'),
('StorageLocation', 'JD01', 'JDPW', N'PndAwali-20011'),
('StorageLocation', 'JD01', 'JDPZ', N'Panda 210 Waziri'),
('StorageLocation', 'JD01', 'JDRA', N'Danube-RwdahAvnu'),
('StorageLocation', 'JD01', 'JDRC', N'Jeddah Rented CS'),
('StorageLocation', 'JD01', 'JDRD', N'Panda AlRiyadh'),
('StorageLocation', 'JD01', 'JDRN', N'Panda Al Rayaan'),
('StorageLocation', 'JD01', 'JDRP', N'Reconditioned Pa'),
('StorageLocation', 'JD01', 'JDRR', N'PANDA-Ar Raw'),
('StorageLocation', 'JD01', 'JDRS', N'Danube-Red Sea M'),
('StorageLocation', 'JD01', 'JDRU', N'Panda Al-Rohaily'),
('StorageLocation', 'JD01', 'JDRW', N'JD Rented Wareho'),
('StorageLocation', 'JD01', 'JDS2', N'Panda 201 Safa'),
('StorageLocation', 'JD01', 'JDSA', N'Panda Al Salam'),
('StorageLocation', 'JD01', 'JDSH', N'Panda Safa 205'),
('StorageLocation', 'JD01', 'JDSL', N'PANDA-Sari'),
('StorageLocation', 'JD01', 'JDSM', N'Panda 208 Sharay'),
('StorageLocation', 'JD01', 'JDSP', N'Main Spare Parts'),
('StorageLocation', 'JD01', 'JDSS', N'Danube Salamah 1'),
('StorageLocation', 'JD01', 'JDST', N'Main Statationar'),
('StorageLocation', 'JD01', 'JDSU', N'Panda 250 Ameer'),
('StorageLocation', 'JD01', 'JDT1', N'Danube-Tahlia 1'),
('StorageLocation', 'JD01', 'JDT2', N'Danube-Tahlia 2'),
('StorageLocation', 'JD01', 'JDTD', N'Technical WH'),
('StorageLocation', 'JD01', 'JDTM', N'Dnub Mall-162'),
('StorageLocation', 'JD01', 'JDTP', N'Dnub Park-180'),
('StorageLocation', 'JD01', 'JDTV', N'DnubVillage-170'),
('StorageLocation', 'JD01', 'JDUJ', N'Panda Ubar Aljun'),
('StorageLocation', 'JD01', 'JDUM', N'Panda Umrah AlJa'),
('StorageLocation', 'JD01', 'JDVL', N'Danube-Village'),
('StorageLocation', 'JD01', 'JDWC', N'Tech WH Contract'),
('StorageLocation', 'JD01', 'JDWS', N'JD01 Workshop'),
('StorageLocation', 'JD01', 'JHDD', N'JD Home DES'),
('StorageLocation', 'JD01', 'MJ01', N'Montana Jedda 01'),
('StorageLocation', 'JD01', 'MJ02', N'Montana Jedda 02'),
('StorageLocation', 'JD01', 'MJ03', N'Montana Jedda 03'),
('StorageLocation', 'JD01', 'MJ04', N'Montana Jedda 04'),
('StorageLocation', 'JD01', 'MJ05', N'Montana Jedda 05'),
('StorageLocation', 'JD01', 'MJ06', N'Montana Jedda 06'),
('StorageLocation', 'JD01', 'MJ07', N'Montana Jedda 07'),
('StorageLocation', 'JD01', 'MJ08', N'Montana Jedda 08'),
('StorageLocation', 'JD01', 'MJ09', N'Montana Jedda 09'),
('StorageLocation', 'JD01', 'MJ10', N'Montana Jedda 10'),
('StorageLocation', 'JD01', 'MJ11', N'Montana Jedda 11'),
('StorageLocation', 'JD01', 'MJ12', N'Montana Jedda 12'),
('StorageLocation', 'JD01', 'MJ13', N'Montana Jedda 13'),
('StorageLocation', 'JD01', 'MJ14', N'Montana Jedda 14'),
('StorageLocation', 'JD01', 'MJ15', N'Montana Jedda 15'),
('StorageLocation', 'JD01', 'MJ16', N'Montana Jedda 16'),
('StorageLocation', 'JD01', 'MJ17', N'Montana Jedda 17'),
('StorageLocation', 'JD01', 'MJ18', N'Montana Jedda 18'),
('StorageLocation', 'JD01', 'MJ19', N'Montana Jedda 19'),
('StorageLocation', 'JD01', 'MJ20', N'Montana Jedda 20'),
('StorageLocation', 'JD01', 'MJ21', N'Montana Jedda 21'),
('StorageLocation', 'JD01', 'MJ22', N'Montana Jedda 22'),
('StorageLocation', 'JD01', 'MJ23', N'Montana Jedda 23'),
('StorageLocation', 'JD01', 'MJ24', N'Montana Jedda 24'),
('StorageLocation', 'JD01', 'MJ25', N'Montana Jedda 25'),
('StorageLocation', 'JD01', 'MJ26', N'Montana 26'),
('StorageLocation', 'JD01', 'MJ27', N'Montana 27'),
('StorageLocation', 'JD01', 'MJ28', N'Montana 28'),
('StorageLocation', 'JD01', 'MJ29', N'Montana 29'),
('StorageLocation', 'JD01', 'MJ30', N'Montana 30'),
('StorageLocation', 'JD01', 'MTJD', N'MONTANA Store Je'),
('StorageLocation', 'JD01', 'VJ01', N'VAN Jeddah 01'),
('StorageLocation', 'JD01', 'VJ02', N'VAN Jeddah 02'),
('StorageLocation', 'JD01', 'VJ03', N'VAN Jeddah 03'),
('StorageLocation', 'JD01', 'VJ04', N'VAN Jeddah 04'),
('StorageLocation', 'JD01', 'VJ05', N'VAN Jeddah 05'),
('StorageLocation', 'JD01', 'VJ06', N'VAN Jeddah 06'),
('StorageLocation', 'JD01', 'VJ07', N'VAN Jeddah 07'),
('StorageLocation', 'JD01', 'VJ08', N'VAN Jeddah 08'),
('StorageLocation', 'JD01', 'VJ09', N'VAN Jeddah 09'),
('StorageLocation', 'JD01', 'VJ10', N'VAN Jeddah 10'),
('StorageLocation', 'JD01', 'VJ11', N'VAN Jeddah 11'),
('StorageLocation', 'JD01', 'VJ12', N'VAN Jeddah 12'),
('StorageLocation', 'JD01', 'VJ13', N'VAN Jeddah 13'),
('StorageLocation', 'JD01', 'VJ14', N'VAN Jeddah 14'),
('StorageLocation', 'JD01', 'VJ15', N'VAN Jeddah 15'),
('StorageLocation', 'JD01', 'VJ16', N'VAN Jeddah 16'),
('StorageLocation', 'JD01', 'VJ17', N'VAN Jeddah 17'),
('StorageLocation', 'JD01', 'VJ18', N'VAN Jeddah 18'),
('StorageLocation', 'JD01', 'VJ19', N'VAN Jeddah 19'),
('StorageLocation', 'JD01', 'VJ20', N'VAN Jeddah 20'),
('StorageLocation', 'JD01', 'VJ21', N'VAN Jeddah 21'),
('StorageLocation', 'JD01', 'VJ22', N'VAN Jeddah 22'),
('StorageLocation', 'JD01', 'VJ23', N'VAN Jeddah 23'),
('StorageLocation', 'JD01', 'VJ24', N'VAN Jeddah 24'),
('StorageLocation', 'JD01', 'Y24', N'Tire Store'),
('StorageLocation', 'JD01', 'Y25', N'Miscellaneous St'),
('StorageLocation', 'JD01', 'Y26', N'Miscellaneous St'),
('StorageLocation', 'JD01', 'Y27', N'Uniform Store 2'),
('StorageLocation', 'JD01', 'Y28', N'Vehicle Old Spar'),
('StorageLocation', 'JD01', 'Y29', N'Open Storage'),
('StorageLocation', 'KH01', 'KHA1', N'Pnd Rd-70006'),
('StorageLocation', 'KH01', 'KHAM', N'Khamis Advertisi'),
('StorageLocation', 'KH01', 'KHAR', N'Danube AlArin'),
('StorageLocation', 'KH01', 'KHBM', N'Pnd Mall-707'),
('StorageLocation', 'KH01', 'KHCS', N'Kh Main CS'),
('StorageLocation', 'KH01', 'KHDS', N'Khamis Destructi'),
('StorageLocation', 'KH01', 'KHFD', N'FDD Store Khamis'),
('StorageLocation', 'KH01', 'KHHD', N'Khamis Home Del'),
('StorageLocation', 'KH01', 'KHHG', N'Khamis Halaga'),
('StorageLocation', 'KH01', 'KHHT', N'KH01 Tran Halaga'),
('StorageLocation', 'KH01', 'KHMW', N'KHAMIS Mntain WH'),
('StorageLocation', 'KH01', 'KHNA', N'Pnd Airprt-70007'),
('StorageLocation', 'KH01', 'KHNZ', N'Danube Nuzha'),
('StorageLocation', 'KH01', 'KHSH', N'Danube Shati'),
('StorageLocation', 'KH01', 'KHTD', N'Khamis Maintenan'),
('StorageLocation', 'KH01', 'KHUS', N'Danube Umsarar'),
('StorageLocation', 'KH01', 'MK01', N'Montana Khami 01'),
('StorageLocation', 'KH01', 'MK02', N'Montana Khami 02'),
('StorageLocation', 'KH01', 'MTKH', N'MONTANA Store Kh'),
('StorageLocation', 'KH01', 'VK01', N'VAN Khamis 01'),
('StorageLocation', 'KH01', 'VK02', N'VAN Khamis 02'),
('StorageLocation', 'KH01', 'VK03', N'VAN Khamis 03'),
('StorageLocation', 'KH01', 'VK04', N'VAN Khamis 04'),
('StorageLocation', 'KH01', 'VK05', N'VAN Khamis 05'),
('StorageLocation', 'KH01', 'VK06', N'VAN Khamis 06'),
('StorageLocation', 'KH01', 'VK07', N'VAN Khamis 07'),
('StorageLocation', 'KH01', 'VK08', N'VAN Khamis 08'),
('StorageLocation', 'KH01', 'VK09', N'VAN Khamis 09'),
('StorageLocation', 'KH01', 'VK10', N'VAN Khamis 10'),
('StorageLocation', 'KH01', 'VK11', N'VAN Khamis 11'),
('StorageLocation', 'KH01', 'VK12', N'VAN Khamis 12'),
('StorageLocation', 'KH01', 'VK13', N'VAN Khamis 13'),
('StorageLocation', 'KH01', 'VK14', N'VAN Khamis 14'),
('StorageLocation', 'KH01', 'VK15', N'VAN Khamis 15'),
('StorageLocation', 'KH01', 'VK16', N'VAN Khamis 16'),
('StorageLocation', 'KH01', 'VK17', N'VAN Khamis 17'),
('StorageLocation', 'KH01', 'VK18', N'VAN Khamis 18'),
('StorageLocation', 'MD01', 'MDA1', N'Pnd Mall-50001'),
('StorageLocation', 'MD01', 'MDAM', N'Madinah Advertis'),
('StorageLocation', 'MD01', 'MDCS', N'MD Main CS'),
('StorageLocation', 'MD01', 'MDDS', N'Madinah Destruct'),
('StorageLocation', 'MD01', 'MDFD', N'FDD Store Madina'),
('StorageLocation', 'MD01', 'MDHA', N'Medinah Halagah'),
('StorageLocation', 'MD01', 'MDHD', N'Madinah Home Del'),
('StorageLocation', 'MD01', 'MDHO', N'Madinah Headoffi'),
('StorageLocation', 'MD01', 'MDHT', N'MD01 Tran Halaga'),
('StorageLocation', 'MD01', 'MDMW', N'MD Mntain WH'),
('StorageLocation', 'MD01', 'MDNM', N'Pnd Mall-50003'),
('StorageLocation', 'MD01', 'MDSA', N'Danube-Sultana'),
('StorageLocation', 'MD01', 'MDTD', N'Madinah Maintena'),
('StorageLocation', 'MD01', 'MM01', N'Montana Madin 01'),
('StorageLocation', 'MD01', 'MM02', N'Montana Madin 02'),
('StorageLocation', 'MD01', 'MM03', N'Montana Madia 03'),
('StorageLocation', 'MD01', 'MM04', N'Montana Madia 04'),
('StorageLocation', 'MD01', 'MM05', N'Montana Madia 05'),
('StorageLocation', 'MD01', 'MTMD', N'MONTA Store Madi'),
('StorageLocation', 'MD01', 'VN01', N'VAN Madinah 01'),
('StorageLocation', 'MD01', 'VN02', N'VAN Madinah 02'),
('StorageLocation', 'MD01', 'VN03', N'VAN Madinah 03'),
('StorageLocation', 'MD01', 'VN04', N'VAN Madinah 04'),
('StorageLocation', 'MD01', 'VN05', N'VAN Madinah 05'),
('StorageLocation', 'MD01', 'VN06', N'VAN Madinah 06'),
('StorageLocation', 'MD01', 'VN07', N'VAN Madinah 07'),
('StorageLocation', 'MD01', 'VN08', N'VAN Madinah 08'),
('StorageLocation', 'MD01', 'VN09', N'VAN Madinah 09'),
('StorageLocation', 'MK01', 'MKAM', N'Makkah Advertisi'),
('StorageLocation', 'MK01', 'MKCS', N'MK Main CS'),
('StorageLocation', 'MK01', 'MKDS', N'Makkah Destruct'),
('StorageLocation', 'MK01', 'MKFD', N'FDD Store Makkah'),
('StorageLocation', 'MK01', 'MKTD', N'Makkah Maintenan'),
('StorageLocation', 'MK01', 'MTMK', N'MONTANA Store Ma'),
('StorageLocation', 'MK01', 'VM01', N'VAN Makkah 01'),
('StorageLocation', 'MK01', 'VM02', N'VAN Makkah 02'),
('StorageLocation', 'MK01', 'VM03', N'VAN Makkah 03'),
('StorageLocation', 'MK01', 'VM04', N'VAN Makkah 04'),
('StorageLocation', 'MK01', 'VM05', N'VAN Makkah 05'),
('StorageLocation', 'MK01', 'VM06', N'VAN Makkah 06'),
('StorageLocation', 'MK01', 'VM07', N'VAN Makkah 07'),
('StorageLocation', 'MK01', 'VM08', N'VAN Makkah 08'),
('StorageLocation', 'MK01', 'VM09', N'VAN Makkah 09'),
('StorageLocation', 'RD01', 'MR01', N'Montana Riyad 01'),
('StorageLocation', 'RD01', 'MR02', N'Montana Riyad 02'),
('StorageLocation', 'RD01', 'MR03', N'Montana Riyad 03'),
('StorageLocation', 'RD01', 'MR04', N'Montana Riyad 04'),
('StorageLocation', 'RD01', 'MR05', N'Montana Riyad 05'),
('StorageLocation', 'RD01', 'MR06', N'Montana Riyad 06'),
('StorageLocation', 'RD01', 'MR07', N'Montana Riyad 07'),
('StorageLocation', 'RD01', 'MR08', N'Montana Riyad 08'),
('StorageLocation', 'RD01', 'MR09', N'Montana Riyad 09'),
('StorageLocation', 'RD01', 'MR10', N'Montana Riyad 10'),
('StorageLocation', 'RD01', 'MR11', N'Montana Riyad 11'),
('StorageLocation', 'RD01', 'MR12', N'Montana Riyad 12'),
('StorageLocation', 'RD01', 'MR13', N'Montana Riyad 13'),
('StorageLocation', 'RD01', 'MR14', N'Montana Riyad 14'),
('StorageLocation', 'RD01', 'MR15', N'Montana Riyad 15'),
('StorageLocation', 'RD01', 'MR16', N'Montana Riyad 16'),
('StorageLocation', 'RD01', 'MR17', N'Montana Riyad 17'),
('StorageLocation', 'RD01', 'MR18', N'Montana Riyad 18'),
('StorageLocation', 'RD01', 'MR19', N'Montana Riyad 19'),
('StorageLocation', 'RD01', 'MR20', N'Montana Riyad 20'),
('StorageLocation', 'RD01', 'MTRD', N'MONTANA Store Ri'),
('StorageLocation', 'RD01', 'RAZ2', N'RD Azizia Sales2'),
('StorageLocation', 'RD01', 'RD1T', N'RD01 Tran  Aziz1'),
('StorageLocation', 'RD01', 'RD2T', N'RD01 Tran  Aziz2'),
('StorageLocation', 'RD01', 'RDAB', N'Panda RD Abubkar'),
('StorageLocation', 'RD01', 'RDAC', N'Labor Accomodati'),
('StorageLocation', 'RD01', 'RDAM', N'RD Adv Material'),
('StorageLocation', 'RD01', 'RDAP', N'Panda 100 Awal P'),
('StorageLocation', 'RD01', 'RDAZ', N'Panda Alaliah Pl'),
('StorageLocation', 'RD01', 'RDCS', N'RD Main CS'),
('StorageLocation', 'RD01', 'RDDS', N'Riyadh Dest WH'),
('StorageLocation', 'RD01', 'RDFD', N'FDD Store Riyadh'),
('StorageLocation', 'RD01', 'RDGM', N'Panda Riyadh Gal'),
('StorageLocation', 'RD01', 'RDHD', N'E-Comm Home Dlvr'),
('StorageLocation', 'RD01', 'RDIA', N'Riyadh Cold stor'),
('StorageLocation', 'RD01', 'RDLW', N'Logistic service'),
('StorageLocation', 'RD01', 'RDMT', N'Panda Al Maathar'),
('StorageLocation', 'RD01', 'RDMW', N'RIYADH Mntain WH'),
('StorageLocation', 'RD01', 'RDOP', N'Panda Al Orobah'),
('StorageLocation', 'RD01', 'RDPL', N'RD PackingLine'),
('StorageLocation', 'RD01', 'RDPT', N'RD01 Tran Pack L'),
('StorageLocation', 'RD01', 'RDRN', N'Panda Rayyan'),
('StorageLocation', 'RD01', 'RDRW', N'Rented Warehouse'),
('StorageLocation', 'RD01', 'RDTD', N'Riyadh Maintenan'),
('StorageLocation', 'RD01', 'RDZ1', N'RD Azizia Sales'),
('StorageLocation', 'RD01', 'RHDD', N'RD Home DES')
) AS s(domain, parent_code, code, description)
    ON  t.domain = s.domain
    AND ISNULL(t.parent_code,'') = ISNULL(s.parent_code,'')
    AND t.code = s.code
WHEN NOT MATCHED THEN
    INSERT (domain, parent_code, code, description, updated_by)
    VALUES (s.domain, s.parent_code, s.code, s.description, 'seed-M10');
GO

-- ---- Seed: storage locations 501-550 ----
MERGE qms.qms_code_description AS t
USING (VALUES
('StorageLocation', 'RD01', 'VR01', N'VAN Riyadh 01'),
('StorageLocation', 'RD01', 'VR02', N'VAN Riyadh 02'),
('StorageLocation', 'RD01', 'VR03', N'VAN Riyadh 03'),
('StorageLocation', 'RD01', 'VR04', N'VAN Riyadh 04'),
('StorageLocation', 'RD01', 'VR05', N'VAN Riyadh 05'),
('StorageLocation', 'RD01', 'VR06', N'VAN Riyadh 06'),
('StorageLocation', 'RD01', 'VR07', N'VAN Riyadh 07'),
('StorageLocation', 'RD01', 'VR08', N'VAN Riyadh 08'),
('StorageLocation', 'RD01', 'VR09', N'VAN Riyadh 09'),
('StorageLocation', 'RD01', 'VR10', N'VAN Riyadh 10'),
('StorageLocation', 'RD01', 'VR11', N'VAN Riyadh 11'),
('StorageLocation', 'RD01', 'VR12', N'VAN Riyadh 12'),
('StorageLocation', 'RD01', 'VR13', N'VAN Riyadh 13'),
('StorageLocation', 'RD01', 'VR14', N'VAN Riyadh 14'),
('StorageLocation', 'RD01', 'VR15', N'VAN Riyadh 15'),
('StorageLocation', 'RD01', 'VR16', N'VAN Riyadh 16'),
('StorageLocation', 'RD01', 'VR17', N'VAN Riyadh 17'),
('StorageLocation', 'RD01', 'VR18', N'VAN Riyadh 18'),
('StorageLocation', 'RD01', 'VR19', N'VAN Riyadh 19'),
('StorageLocation', 'RD01', 'VR20', N'VAN Riyadh 20'),
('StorageLocation', 'RD01', 'VR21', N'VAN Riyadh 21'),
('StorageLocation', 'RD01', 'VR22', N'VAN Riyadh 22'),
('StorageLocation', 'RD01', 'VR23', N'VAN Riyadh 23'),
('StorageLocation', 'RD01', 'VR24', N'VAN Riyadh 24'),
('StorageLocation', 'RD01', 'VR25', N'VAN Riyadh 25'),
('StorageLocation', 'RD01', 'VR26', N'VAN Riyadh 25'),
('StorageLocation', 'RD02', '0001', N'Lager 0001'),
('StorageLocation', 'RD02', '0088', N'Lager 0088 (WM)'),
('StorageLocation', 'RD02', '0100', N'Lagerort WM&HU'),
('StorageLocation', 'RD02', '0200', N'SCM-EWM'),
('StorageLocation', 'RD02', 'RDIA', N'RD CS indus area'),
('StorageLocation', 'RD02', 'RDIL', N'RD CS indust Lbr'),
('StorageLocation', 'TB01', 'MT01', N'Montana Tabuk 01'),
('StorageLocation', 'TB01', 'MTTB', N'MONTANA Store Ta'),
('StorageLocation', 'TB01', 'TBAM', N'TB Adv Material'),
('StorageLocation', 'TB01', 'TBCS', N'TB Main CS'),
('StorageLocation', 'TB01', 'TBDS', N'Tabuk Destructio'),
('StorageLocation', 'TB01', 'TBFD', N'FDD Store Tabouk'),
('StorageLocation', 'TB01', 'TBHA', N'Tabuk Halaga'),
('StorageLocation', 'TB01', 'TBHD', N'Tabuk Home Del'),
('StorageLocation', 'TB01', 'TBHT', N'TB01 Tran Halaga'),
('StorageLocation', 'TB01', 'TBTD', N'Tabuk Maintenanc'),
('StorageLocation', 'TB01', 'VT01', N'VAN Tabuk 01'),
('StorageLocation', 'TB01', 'VT02', N'VAN Tabuk 02'),
('StorageLocation', 'TB01', 'VT03', N'VAN Tabuk 03'),
('StorageLocation', 'TB01', 'VT04', N'VAN Tabuk 04'),
('StorageLocation', 'TB01', 'VT05', N'VAN Tabuk 05'),
('StorageLocation', 'TB01', 'VT06', N'VAN Tabuk 06'),
('StorageLocation', 'TB01', 'VT07', N'VAN Tabuk 07'),
('StorageLocation', 'TB01', 'VT08', N'VAN Tabuk 08')
) AS s(domain, parent_code, code, description)
    ON  t.domain = s.domain
    AND ISNULL(t.parent_code,'') = ISNULL(s.parent_code,'')
    AND t.code = s.code
WHEN NOT MATCHED THEN
    INSERT (domain, parent_code, code, description, updated_by)
    VALUES (s.domain, s.parent_code, s.code, s.description, 'seed-M10');
GO

-- ---- Seed: PO types actually seen in the container cache ----
-- No SAP master exists for EKKO.BSART texts, so description starts as the
-- code itself; an admin renames them in Parameters > Code Descriptions.
INSERT INTO qms.qms_code_description (domain, parent_code, code, description, updated_by)
SELECT DISTINCT 'PoType', NULL, c.po_type, c.po_type, 'seed-M10'
FROM   qms.qms_sap_container_cache c
WHERE  c.po_type IS NOT NULL
  AND  c.po_type <> ''
  AND  NOT EXISTS (SELECT 1 FROM qms.qms_code_description d
                   WHERE d.domain = 'PoType' AND d.code = c.po_type);
GO

-- The three codes the cache actually holds, named from what the business calls
-- them. Only applied where the description is still the placeholder code, so an
-- admin's own wording is never overwritten by a re-run.
UPDATE qms.qms_code_description
SET    description = v.name, updated_by = 'seed-M10'
FROM   qms.qms_code_description d
JOIN   (VALUES ('ZFAS', N'Air Shipment'),
               ('ZFCO', N'Consignment'),
               ('ZFFP', N'Firm')) AS v(code, name) ON v.code = d.code
WHERE  d.domain = 'PoType' AND d.description = d.code;
GO

SELECT 'code_desc_plant'   AS check_item, COUNT(*) AS value FROM qms.qms_code_description WHERE domain = 'Plant';            -- expect 12
SELECT 'code_desc_storage' AS check_item, COUNT(*) AS value FROM qms.qms_code_description WHERE domain = 'StorageLocation';  -- expect 550
SELECT 'code_desc_potype'  AS check_item, COUNT(*) AS value FROM qms.qms_code_description WHERE domain = 'PoType';
