-- ============================================================================
--  SharbatlyQMS on Sharbatly_MIS  -  M29  -  seed the label catalogue
-- ============================================================================
--  Labels are normally DISCOVERED: rendering one records it, and a background
--  flush writes the row. That is what keeps the catalogue honest -- it lists
--  what the screens actually print, with no registry to fall out of step.
--
--  Discovery alone would mean Admin -> Labels starts empty after a deployment
--  and fills in only as people happen to walk the application, which reads as a
--  broken page rather than as an empty one. So the 519 captions the views ship
--  are seeded here, taken from the same pass that wrapped them.
--
--  INSERT-if-missing only: custom_text is never touched, so re-running this
--  after an administrator has renamed things changes nothing they did.
--
--  Idempotent: safe to re-run.
-- ============================================================================

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'% of Σ size — (Σ value ÷ Σ sample size) × 100', N'Admin'),
    (N'(any)', N'Reports'),
    (N'(choose group…)', N'Admin'),
    (N'(no perspective loaded)', N'Reports'),
    (N'(use global default)', N'Reports'),
    (N'+ Calculated', N'Reports'),
    (N'+ Empty', N'Reports'),
    (N'+ Total', N'Reports'),
    (N'-- choose a material group --', N'Admin'),
    (N'0   (integer)', N'Reports'),
    (N'0%   (percent)', N'Reports'),
    (N'0.0  (1 decimal)', N'Reports'),
    (N'0.00 (2 decimals)', N'Reports'),
    (N'About', N'Audit'),
    (N'Access denied', N'Account'),
    (N'Access to this screen', N'Security'),
    (N'Action', N'Arrivals'),
    (N'Actions', N'QualityOrders'),
    (N'Active', N'Security'),
    (N'Active Directory', N'Admin'),
    (N'Activity log', N'Audit'),
    (N'Add Note', N'ClaimManagement'),
    (N'Add arrival field', N'Admin'),
    (N'Add category', N'Admin'),
    (N'Add defect', N'Admin'),
    (N'Add description', N'Admin'),
    (N'Add filter', N'Reports'),
    (N'Add header field', N'Admin'),
    (N'Add measure', N'Reports'),
    (N'Add note', N'ClaimManagement'),
    (N'Add reading type', N'Admin'),
    (N'Add sample', N'QualityOrders'),
    (N'Add user from AD', N'Admin'),
    (N'Add user from Active Directory', N'Admin'),
    (N'Admin', N'Shared'),
    (N'Admin → Sample Headers', N'QualityOrders'),
    (N'Aggregation', N'Reports'),
    (N'Alert Thresholds', N'Admin'),
    (N'All', N'Home'),
    (N'All material groups', N'Admin'),
    (N'All plants', N'QualityOrders'),
    (N'All roles', N'Admin'),
    (N'All statuses', N'Admin'),
    (N'All storage locations', N'QualityOrders'),
    (N'All suppliers', N'QualityOrders'),
    (N'Also attach', N'QualityOrders'),
    (N'Always CC', N'QualityOrders'),
    (N'Any plant', N'Audit'),
    (N'Any supplier', N'Audit'),
    (N'Any user or role', N'Audit'),
    (N'Anyone', N'QualityOrders'),
    (N'Apply', N'Reports'),
    (N'Apply filters', N'QualityOrders'),
    (N'Archive by PO date', N'Arrivals'),
    (N'Archive by date', N'Arrivals'),
    (N'Archive range', N'Arrivals'),
    (N'Archived', N'ClaimManagement'),
    (N'Arrival', N'QualityOrders'),
    (N'Arrival #', N'Arrivals'),
    (N'Arrival Date', N'Reports'),
    (N'Arrival Field Rules', N'Shared'),
    (N'Arrival Fields', N'Shared'),
    (N'Arrival No', N'ClaimManagement'),
    (N'Arrival already exists', N'Arrivals'),
    (N'Arrival date', N'Arrivals'),
    (N'Arrival date from', N'Arrivals'),
    (N'Arrival date to', N'Arrivals'),
    (N'Arrival id', N'Reports'),
    (N'Arrival no.', N'QualityOrders'),
    (N'Arrivals', N'Shared'),
    (N'Arrivals → Pending Containers', N'Admin'),
    (N'Audit Log', N'Shared'),
    (N'Auto', N'Reports'),
    (N'Auto-sync', N'Admin'),
    (N'Average — Σ value ÷ sample count (e.g. Gross / Net weight)', N'Admin'),
    (N'BOL', N'Reports'),
    (N'BOL No', N'Reports'),
    (N'BOL number', N'Arrivals'),
    (N'Back', N'QualityOrders'),
    (N'Back (°C)', N'Arrivals'),
    (N'Back to QO', N'QualityOrders'),
    (N'Back to arrivals', N'Arrivals'),
    (N'Back to dashboard', N'Shared'),
    (N'Batch', N'Arrivals'),
    (N'Become self', N'Shared'),
    (N'Becomes', N'Admin'),
    (N'Blue', N'Shared'),
    (N'Body *', N'QualityOrders'),
    (N'Branding', N'Admin'),
    (N'Brix', N'QualityOrders'),
    (N'CC', N'QualityOrders'),
    (N'Can open this screen', N'Security'),
    (N'Cancel', N'Security'),
    (N'Cancel submit', N'QualityOrders'),
    (N'Cancel — add samples first', N'QualityOrders'),
    (N'Cancelled', N'Reports'),
    (N'Carrier Name', N'Arrivals'),
    (N'Category', N'Shared'),
    (N'Category *', N'Admin'),
    (N'Changed by', N'Audit')
) AS s (label_key, screen_key)
    ON t.label_key = s.label_key
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key) VALUES (s.label_key, NULLIF(s.screen_key, N''));
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Claim Status', N'ClaimManagement'),
    (N'Claim owner', N'ClaimManagement'),
    (N'Claims', N'Shared'),
    (N'Class', N'Reports'),
    (N'Clear', N'QualityOrders'),
    (N'Clear all', N'Audit'),
    (N'Clear all filters', N'Reports'),
    (N'Clear every row', N'Admin'),
    (N'Clear selection', N'Reports'),
    (N'Clear them', N'Audit'),
    (N'Close', N'QualityOrders'),
    (N'Closed', N'ClaimManagement'),
    (N'Closed By', N'ClaimManagement'),
    (N'Closed by', N'ClaimManagement'),
    (N'Closed from', N'ClaimManagement'),
    (N'Closed to', N'ClaimManagement'),
    (N'Code', N'Admin'),
    (N'Code *', N'Admin'),
    (N'Code Descriptions', N'Shared'),
    (N'Collapse all', N'Security'),
    (N'Colour', N'Admin'),
    (N'Compare all roles', N'Security'),
    (N'Complete arrival', N'Arrivals'),
    (N'Configure AD', N'Admin'),
    (N'Confirm new password', N'Account'),
    (N'Contain (whole image visible)', N'Admin'),
    (N'Container', N'Reports'),
    (N'Container No', N'Reports'),
    (N'Container number', N'Arrivals'),
    (N'Count — number of samples with a value', N'Admin'),
    (N'Country of origin', N'Arrivals'),
    (N'Cover (crop to fill)', N'Admin'),
    (N'Coverage', N'Home'),
    (N'Create', N'Arrivals'),
    (N'Create Quality Order', N'Arrivals'),
    (N'Create arrival', N'Arrivals'),
    (N'Create role', N'Security'),
    (N'Created', N'QualityOrders'),
    (N'Created By', N'Arrivals'),
    (N'Created by', N'Arrivals'),
    (N'Created from', N'QualityOrders'),
    (N'Created to', N'QualityOrders'),
    (N'Current folder in use', N'Admin'),
    (N'Current password', N'Account'),
    (N'Custom column label (optional)', N'Reports'),
    (N'Dark', N'Shared'),
    (N'Dashboard', N'Home'),
    (N'Data Hub', N'Reports'),
    (N'Data hub', N'Shared'),
    (N'Date code', N'QualityOrders'),
    (N'Date — date picker', N'Admin'),
    (N'Dates', N'Arrivals'),
    (N'Default unit', N'Admin'),
    (N'Defect', N'Reports'),
    (N'Defect % red threshold', N'Admin'),
    (N'Defect % yellow threshold', N'Admin'),
    (N'Defect Catalog', N'Shared'),
    (N'Defect Categories', N'Shared'),
    (N'Defect Category', N'Reports'),
    (N'Delete', N'Reports'),
    (N'Delete permanently', N'QualityOrders'),
    (N'Delete sample', N'QualityOrders'),
    (N'Delete selected', N'Admin'),
    (N'Delete this role', N'Security'),
    (N'Department', N'Security'),
    (N'Description', N'Security'),
    (N'Dimension', N'Reports'),
    (N'Disabled', N'Admin'),
    (N'Display Temp (°C)', N'Arrivals'),
    (N'Documents', N'QualityOrders'),
    (N'Domain *', N'Admin'),
    (N'Download', N'QualityOrders'),
    (N'Download Excel', N'Reports'),
    (N'Download PDF report', N'QualityOrders'),
    (N'Download checklist PDF', N'Arrivals'),
    (N'Edit', N'Arrivals'),
    (N'Editable when closed', N'Admin'),
    (N'Email', N'Security'),
    (N'Email (SMTP)', N'Admin'),
    (N'Employee ID', N'Admin'),
    (N'Enable scheduled auto-sync', N'Admin'),
    (N'Endpoint', N'Admin'),
    (N'Everything', N'Audit'),
    (N'Examination date', N'Arrivals'),
    (N'Example', N'Admin'),
    (N'Expand all', N'Security'),
    (N'Export pivot to Excel', N'Reports'),
    (N'Export to Excel', N'Reports'),
    (N'Field', N'Admin'),
    (N'File', N'Shared'),
    (N'Files', N'Shared'),
    (N'Filter', N'Reports'),
    (N'Finish Quality Order', N'QualityOrders'),
    (N'Finish order', N'QualityOrders'),
    (N'Finished', N'Reports'),
    (N'Firmness', N'QualityOrders'),
    (N'Fit mode', N'Admin'),
    (N'Flat defects (data hub)', N'Reports'),
    (N'Flat defects — data hub', N'Reports'),
    (N'Forest', N'Shared')
) AS s (label_key, screen_key)
    ON t.label_key = s.label_key
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key) VALUES (s.label_key, NULLIF(s.screen_key, N''));
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Formula — placeholder, renders as “—” for now', N'Admin'),
    (N'From', N'Audit'),
    (N'From email', N'Admin'),
    (N'From name', N'Admin'),
    (N'Front (°C)', N'Arrivals'),
    (N'Full name', N'Security'),
    (N'Full name *', N'Account'),
    (N'Group', N'Admin'),
    (N'Grower', N'QualityOrders'),
    (N'Heat (per measure)', N'Reports'),
    (N'Hide 0s', N'Reports'),
    (N'Hold Notification', N'ClaimManagement'),
    (N'Hours', N'Admin'),
    (N'I understand and want to finish this Quality Order.', N'QualityOrders'),
    (N'Images', N'Arrivals'),
    (N'Images / Thumbnails', N'Admin'),
    (N'Initial', N'Reports'),
    (N'Inspection Checklist', N'Arrivals'),
    (N'Inspection date', N'Arrivals'),
    (N'Keep me signed in for 30 days', N'Account'),
    (N'Kind', N'Audit'),
    (N'LDAP path', N'Admin'),
    (N'Labels', N'Shared'),
    (N'Last activity', N'ClaimManagement'),
    (N'Last sync', N'Admin'),
    (N'Light', N'Shared'),
    (N'Lines', N'Arrivals'),
    (N'Loading date', N'Arrivals'),
    (N'Loading port', N'Arrivals'),
    (N'Logger temp (°C)', N'Arrivals'),
    (N'Lot', N'QualityOrders'),
    (N'Mail Template', N'Shared'),
    (N'Major Cat', N'Reports'),
    (N'Major Category', N'Reports'),
    (N'Major category', N'Arrivals'),
    (N'Manage on the Users screen', N'Security'),
    (N'Mandatory', N'Admin'),
    (N'Mark as Claim Notification Request', N'ClaimManagement'),
    (N'Mark as Passed QC', N'ClaimManagement'),
    (N'Mark as Reviewed', N'ClaimManagement'),
    (N'Material', N'Reports'),
    (N'Material Group', N'Reports'),
    (N'Material details', N'QualityOrders'),
    (N'Material group', N'Reports'),
    (N'Material group *', N'Admin'),
    (N'Material — entered once per material, inherited by every sample', N'Admin'),
    (N'Materials', N'QualityOrders'),
    (N'Materials without samples', N'QualityOrders'),
    (N'Measure', N'Reports'),
    (N'Measure to chart', N'Reports'),
    (N'Middle (°C)', N'Arrivals'),
    (N'Move container', N'Arrivals'),
    (N'Move container to plant', N'Arrivals'),
    (N'Multi Carton', N'Reports'),
    (N'My Profile', N'Shared'),
    (N'Name', N'Reports'),
    (N'Name *', N'Admin'),
    (N'New arrival from SAP', N'Arrivals'),
    (N'New password', N'Account'),
    (N'New password (min 6 chars)', N'Admin'),
    (N'New role', N'Security'),
    (N'New sample size *', N'QualityOrders'),
    (N'No', N'Arrivals'),
    (N'No access', N'Security'),
    (N'None', N'Security'),
    (N'Notes', N'ClaimManagement'),
    (N'Nothing — start with no permissions', N'Security'),
    (N'Notifications', N'Shared'),
    (N'Number format (fallback)', N'Reports'),
    (N'Number format (optional override)', N'Reports'),
    (N'Numeric', N'Admin'),
    (N'Numeric — number input', N'Admin'),
    (N'One Carton', N'Reports'),
    (N'Open', N'Reports'),
    (N'Open Quality Order', N'Arrivals'),
    (N'Open Quality Order days', N'Admin'),
    (N'Open existing arrival', N'Arrivals'),
    (N'Open in new tab', N'QualityOrders'),
    (N'Open with this perspective by default', N'Reports'),
    (N'Opened', N'Home'),
    (N'Opened By', N'QualityOrders'),
    (N'Opened by', N'QualityOrders'),
    (N'Order', N'Admin'),
    (N'Order Status', N'ClaimManagement'),
    (N'Origin', N'Reports'),
    (N'Outstanding', N'Home'),
    (N'Override sample size (inspected qty)', N'QualityOrders'),
    (N'Override size', N'QualityOrders'),
    (N'PDF summary', N'Admin'),
    (N'PDF summary mode', N'Admin'),
    (N'PDF thumbnail height (px)', N'Admin'),
    (N'PDF thumbnail width (px)', N'Admin'),
    (N'PO', N'Reports'),
    (N'PO (EBELN)', N'Arrivals'),
    (N'PO (Ebeln)', N'Reports'),
    (N'PO / Item', N'Arrivals'),
    (N'PO / STO', N'Arrivals'),
    (N'PO Date', N'Reports'),
    (N'PO Qty', N'Reports'),
    (N'PO date from', N'Reports')
) AS s (label_key, screen_key)
    ON t.label_key = s.label_key
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key) VALUES (s.label_key, NULLIF(s.screen_key, N''));
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'PO date to', N'Reports'),
    (N'PO from', N'Reports'),
    (N'PO to', N'Reports'),
    (N'PO type', N'Arrivals'),
    (N'Pallet', N'QualityOrders'),
    (N'Parameters', N'Shared'),
    (N'Password', N'Account'),
    (N'Pending', N'Arrivals'),
    (N'Pending Containers', N'Shared'),
    (N'Pending Containers retrieval', N'Admin'),
    (N'Percentage', N'Shared'),
    (N'Permission', N'Security'),
    (N'Permissions', N'Security'),
    (N'Person', N'Audit'),
    (N'Placeholder', N'Admin'),
    (N'Plant', N'Security'),
    (N'Plant / Storage', N'Arrivals'),
    (N'Port', N'Admin'),
    (N'Preview', N'Reports'),
    (N'Preview QC report', N'QualityOrders'),
    (N'Procurement type', N'Arrivals'),
    (N'Products', N'ClaimManagement'),
    (N'Pull every (minutes)', N'Admin'),
    (N'Pull now', N'Admin'),
    (N'QC Assessment', N'ClaimManagement'),
    (N'QC created', N'Home'),
    (N'QC number', N'QualityOrders'),
    (N'QO', N'Reports'),
    (N'QO Number', N'QualityOrders'),
    (N'QO Status', N'Reports'),
    (N'QO id', N'Reports'),
    (N'Qty', N'Arrivals'),
    (N'Quality Order', N'Arrivals'),
    (N'Quality Orders', N'Shared'),
    (N'Re-open arrival for edit', N'Arrivals'),
    (N'Re-open for edit', N'Arrivals'),
    (N'Read only', N'Security'),
    (N'Reading Types', N'Shared'),
    (N'Reason', N'Arrivals'),
    (N'Reason (required)', N'QualityOrders'),
    (N'Receive Date', N'Reports'),
    (N'Receive date', N'Arrivals'),
    (N'Received', N'Home'),
    (N'Refresh', N'QualityOrders'),
    (N'Refresh list', N'Security'),
    (N'Remove current logo', N'Admin'),
    (N'Remove uploaded image', N'Admin'),
    (N'Renderer', N'Reports'),
    (N'Reopen', N'QualityOrders'),
    (N'Reopen Quality Order', N'QualityOrders'),
    (N'Report', N'Admin'),
    (N'Report Builder', N'Reports'),
    (N'Report Units', N'Shared'),
    (N'Report builder', N'Shared'),
    (N'Report layout', N'Admin'),
    (N'Report name', N'Reports'),
    (N'Reports', N'Shared'),
    (N'Reset', N'Reports'),
    (N'Reset these filters', N'QualityOrders'),
    (N'Restore', N'Arrivals'),
    (N'Restore by PO date', N'Arrivals'),
    (N'Restore by date', N'Arrivals'),
    (N'Restore range', N'Arrivals'),
    (N'Result', N'Admin'),
    (N'Retrieve latest containers', N'Arrivals'),
    (N'Role', N'Admin'),
    (N'Role editor', N'Security'),
    (N'Role name', N'Security'),
    (N'Roles only', N'Audit'),
    (N'Rose', N'Shared'),
    (N'Rows', N'Admin'),
    (N'Run', N'Reports'),
    (N'SAP OData', N'Admin'),
    (N'SAP code', N'Admin'),
    (N'SMTP host', N'Admin'),
    (N'SMTP password', N'Admin'),
    (N'SMTP username', N'Admin'),
    (N'Sample #', N'Reports'),
    (N'Sample Header Fields', N'Admin'),
    (N'Sample Headers', N'Shared'),
    (N'Sample Scope', N'Reports'),
    (N'Sample size', N'Reports'),
    (N'Sample — entered on every sample', N'Admin'),
    (N'Save', N'Reports'),
    (N'Save AD settings', N'Admin'),
    (N'Save SAP settings', N'Admin'),
    (N'Save SMTP settings', N'Admin'),
    (N'Save alert thresholds', N'Admin'),
    (N'Save all roles', N'Security'),
    (N'Save as…', N'Reports'),
    (N'Save branding text', N'Admin'),
    (N'Save changes', N'Account'),
    (N'Save details', N'Security'),
    (N'Save material details', N'QualityOrders'),
    (N'Save override', N'QualityOrders'),
    (N'Save perspective', N'Reports'),
    (N'Save recipients', N'Admin'),
    (N'Save report options', N'Admin'),
    (N'Save rules', N'Admin'),
    (N'Save sample', N'QualityOrders')
) AS s (label_key, screen_key)
    ON t.label_key = s.label_key
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key) VALUES (s.label_key, NULLIF(s.screen_key, N''));
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Save settings', N'Admin'),
    (N'Save shipment details', N'Arrivals'),
    (N'Save storage folder', N'Admin'),
    (N'Save template', N'Admin'),
    (N'Save thumbnail settings', N'Admin'),
    (N'Save units', N'Admin'),
    (N'Saved designs', N'Reports'),
    (N'Scheduled hours (24-hour clock, comma-separated)', N'Admin'),
    (N'Scope', N'Admin'),
    (N'Scope *', N'Admin'),
    (N'Screen', N'Security'),
    (N'Screen thumbnail height (px)', N'Admin'),
    (N'Screen thumbnail width (px)', N'Admin'),
    (N'Search', N'Audit'),
    (N'Search SAP', N'Arrivals'),
    (N'Search SAP directly', N'Arrivals'),
    (N'Search SAP shipment', N'Arrivals'),
    (N'Search values', N'Reports'),
    (N'Security', N'Shared'),
    (N'Select all', N'Security'),
    (N'Select all visible', N'Reports'),
    (N'Send', N'QualityOrders'),
    (N'Send report to supplier', N'QualityOrders'),
    (N'Send test', N'Admin'),
    (N'Send test email to', N'Admin'),
    (N'Sepia', N'Shared'),
    (N'Service account password', N'Admin'),
    (N'Service account user', N'Admin'),
    (N'Set Temp (°C)', N'Arrivals'),
    (N'Set as default', N'Reports'),
    (N'Sharbatly QMS', N'Account'),
    (N'Shared', N'Reports'),
    (N'Shipment', N'Arrivals'),
    (N'Shipping Date', N'Reports'),
    (N'Show', N'Arrivals'),
    (N'Show all records', N'QualityOrders'),
    (N'Sign in', N'Account'),
    (N'Sign out', N'Shared'),
    (N'Site Configuration', N'Shared'),
    (N'Site Configuration → SAP', N'Home'),
    (N'Site URL (used in email links)', N'Admin'),
    (N'Site name', N'Admin'),
    (N'Size', N'Shared'),
    (N'Something went wrong', N'Shared'),
    (N'Sort order', N'Admin'),
    (N'Stale arrival (Draft) days', N'Admin'),
    (N'Start date (Doc_Date ≥)', N'Admin'),
    (N'Start from', N'Security'),
    (N'Status', N'Security'),
    (N'Stop previewing', N'Shared'),
    (N'Storage', N'Arrivals'),
    (N'Storage Loc', N'Reports'),
    (N'Storage Loc.', N'Reports'),
    (N'Storage location', N'QualityOrders'),
    (N'Sub Cat', N'Reports'),
    (N'Subject *', N'QualityOrders'),
    (N'Submit', N'QualityOrders'),
    (N'Submitted', N'Reports'),
    (N'Sum — total of numeric values', N'Admin'),
    (N'Summary', N'Arrivals'),
    (N'Supplier', N'Reports'),
    (N'Supplier (name contains)', N'Reports'),
    (N'Sync Status', N'Admin'),
    (N'Sync now', N'Admin'),
    (N'Tare weight', N'QualityOrders'),
    (N'Test', N'Admin'),
    (N'Test connection', N'Admin'),
    (N'Text', N'Admin'),
    (N'Text join — distinct values, comma-separated', N'Admin'),
    (N'Text — free text input', N'Admin'),
    (N'Theme', N'Shared'),
    (N'Time Bar basis', N'Admin'),
    (N'To', N'Audit'),
    (N'To *', N'QualityOrders'),
    (N'Top N rows', N'Reports'),
    (N'Transit', N'Arrivals'),
    (N'Transit Days', N'Reports'),
    (N'Transit days', N'Arrivals'),
    (N'Type', N'Arrivals'),
    (N'Unit', N'Admin'),
    (N'Unit on report', N'Admin'),
    (N'UoM', N'Arrivals'),
    (N'Update password', N'Account'),
    (N'Updated', N'Admin'),
    (N'Upload', N'Shared'),
    (N'Upload new logo', N'Admin'),
    (N'Upload picture', N'Account'),
    (N'Uploaded', N'Shared'),
    (N'Uploaded by', N'Shared'),
    (N'Uploads disk full alert (%)', N'Admin'),
    (N'Uploads folder (absolute path)', N'Admin'),
    (N'Use TLS / SSL', N'Admin'),
    (N'Username', N'Security'),
    (N'Users', N'Shared'),
    (N'Users and roles', N'Audit'),
    (N'Users only', N'Audit'),
    (N'Value', N'Reports'),
    (N'Value kind *', N'Admin'),
    (N'Value type', N'Admin'),
    (N'Value type *', N'Admin')
) AS s (label_key, screen_key)
    ON t.label_key = s.label_key
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key) VALUES (s.label_key, NULLIF(s.screen_key, N''));
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Variety', N'Reports'),
    (N'Vendor', N'Home'),
    (N'Vendor No (exact)', N'Reports'),
    (N'Vessel name', N'Arrivals'),
    (N'View', N'Arrivals'),
    (N'View arrival', N'QualityOrders'),
    (N'View site as', N'Shared'),
    (N'Visibility', N'Reports'),
    (N'Voyage number', N'Arrivals'),
    (N'What happened', N'Audit'),
    (N'When', N'Audit'),
    (N'Yes', N'Arrivals'),
    (N'Yes / No — dropdown', N'Admin'),
    (N'show more / less', N'Audit'),
    (N'— all —', N'Reports'),
    (N'— new report —', N'Reports'),
    (N'— pick a group —', N'Reports'),
    (N'— pick the owning plant —', N'Admin'),
    (N'🌐 Global — applies to every material group', N'Admin')
) AS s (label_key, screen_key)
    ON t.label_key = s.label_key
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key) VALUES (s.label_key, NULLIF(s.screen_key, N''));
GO

SELECT 'seeded_labels' AS check_item, CAST(COUNT(*) AS VARCHAR(20)) AS value FROM qms.qms_ui_label
UNION ALL
SELECT 'overridden',    CAST(COUNT(*) AS VARCHAR(20)) FROM qms.qms_ui_label WHERE custom_text IS NOT NULL;
GO
