-- ============================================================================
--  SharbatlyQMS on Sharbatly_MIS  -  M30  -  label KINDS, and the field labels
-- ============================================================================
--  Two things at once, because they answer the same complaint.
--
--  1. The first label pass reached grid headers, buttons, links, headings and
--     page titles. It did not reach FIELD labels -- "Discharge Date" and the
--     rest of the label/value rows, definition lists and required-marked form
--     labels -- which is most of what anyone actually wants to rename. Those
--     are wrapped now, taking the catalogue to 917 labels.
--
--  2. At 917 entries one alphabetical list is not navigable. Each label now
--     carries the KIND of thing it is -- Field label, Column header, Button,
--     Heading, Dropdown option, Placeholder, Link, Caption -- derived from the
--     element it sits in, so it cannot drift from what the view renders. The
--     admin page filters on it.
--
--  kind is NULL for labels discovered at runtime after this migration: the
--  renderer sees the text, not the markup around it. The admin page shows those
--  as "Other", which is honest -- and re-running the wrapper reclassifies them.
--
--  Idempotent: custom_text is never touched, so an administrator's renames
--  survive a re-run.
-- ============================================================================

IF COL_LENGTH('qms.qms_ui_label', 'kind') IS NULL
    ALTER TABLE qms.qms_ui_label ADD kind NVARCHAR(32) NULL;
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'#RRGGBB', N'Admin', N'Placeholder'),
    (N'% of Σ size — (Σ value ÷ Σ sample size) × 100', N'Admin', N'Dropdown option'),
    (N'(any)', N'Reports', N'Dropdown option'),
    (N'(choose group…)', N'Admin', N'Dropdown option'),
    (N'(click + to add, or drag a chip)', N'Reports', N'Caption'),
    (N'(click to expand / collapse — last state remembered)', N'Reports', N'Caption'),
    (N'(company logo on the Quality Control Report — 100% = original size)', N'Admin', N'Caption'),
    (N'(empty)', N'Audit', N'Caption'),
    (N'(global default)', N'Admin', N'Caption'),
    (N'(managers and site admins only)', N'Reports', N'Caption'),
    (N'(no perspective loaded)', N'Reports', N'Dropdown option'),
    (N'(none ticked = all)', N'Admin', N'Caption'),
    (N'(optional)', N'QualityOrders', N'Caption'),
    (N'(reused next time; CC is never saved)', N'QualityOrders', N'Caption'),
    (N'(shown above every report title)', N'Admin', N'Caption'),
    (N'(small text at the bottom of every PDF page)', N'Admin', N'Caption'),
    (N'(up to 4)', N'Arrivals', N'Caption'),
    (N'(use global default)', N'Reports', N'Dropdown option'),
    (N'+ Calculated', N'Reports', N'Button'),
    (N'+ Empty', N'Reports', N'Button'),
    (N'+ Total', N'Reports', N'Button'),
    (N'-- choose a material group --', N'Admin', N'Dropdown option'),
    (N'0   (integer)', N'Reports', N'Dropdown option'),
    (N'0%   (percent)', N'Reports', N'Dropdown option'),
    (N'0.0  (1 decimal)', N'Reports', N'Dropdown option'),
    (N'0.00 (2 decimals)', N'Reports', N'Dropdown option'),
    (N'0s', N'QualityOrders', N'Caption'),
    (N'1. External Inspection', N'Arrivals', N'Caption'),
    (N'2. Internal Inspection', N'Arrivals', N'Caption'),
    (N'3. Pulp Temperature Check', N'Arrivals', N'Caption'),
    (N'4. Data Logger Inspection', N'Arrivals', N'Caption'),
    (N'5. Notes / Observations', N'Arrivals', N'Caption'),
    (N'6. Photo Attachments Checklist', N'Arrivals', N'Field label'),
    (N'ARR-…', N'QualityOrders', N'Placeholder'),
    (N'About', N'Audit', N'Field label'),
    (N'Access denied', N'Account', N'Heading'),
    (N'Access to this screen', N'Security', N'Field label'),
    (N'Action', N'Arrivals', N'Column header'),
    (N'Actions', N'QualityOrders', N'Column header'),
    (N'Active', N'Security', N'Field label'),
    (N'Active Directory', N'Admin', N'Button'),
    (N'Active Directory (domain sign-in)', N'Admin', N'Caption'),
    (N'Activity log', N'Audit', N'Link'),
    (N'Add Note', N'ClaimManagement', N'Button'),
    (N'Add a note about this order…', N'QualityOrders', N'Placeholder'),
    (N'Add a note without changing claim status...', N'ClaimManagement', N'Placeholder'),
    (N'Add arrival field', N'Admin', N'Button'),
    (N'Add category', N'Admin', N'Button'),
    (N'Add defect', N'Admin', N'Heading'),
    (N'Add description', N'Admin', N'Button'),
    (N'Add filter', N'Reports', N'Button'),
    (N'Add header field', N'Admin', N'Button'),
    (N'Add measure', N'Reports', N'Button'),
    (N'Add note', N'ClaimManagement', N'Caption'),
    (N'Add reading type', N'Admin', N'Heading'),
    (N'Add sample', N'QualityOrders', N'Button'),
    (N'Add user from AD', N'Admin', N'Button'),
    (N'Add user from Active Directory', N'Admin', N'Heading'),
    (N'Additional Fields', N'Shared', N'Field label'),
    (N'Address taken from the SAP vendor master.', N'QualityOrders', N'Caption'),
    (N'Admin', N'Shared', N'Link'),
    (N'Admin → Sample Headers', N'QualityOrders', N'Link'),
    (N'Administration', N'Audit', N'Caption'),
    (N'Administrators always see every plant, so no plant assignment is needed.', N'Admin', N'Caption'),
    (N'After', N'Audit', N'Caption'),
    (N'Aged Open QOs', N'Home', N'Caption'),
    (N'Aggregation', N'Reports', N'Field label'),
    (N'Alert Thresholds', N'Admin', N'Button'),
    (N'Alert thresholds', N'Admin', N'Caption'),
    (N'All', N'Home', N'Dropdown option'),
    (N'All material groups', N'Admin', N'Dropdown option'),
    (N'All plants', N'Admin', N'Dropdown option'),
    (N'All roles', N'Admin', N'Dropdown option'),
    (N'All statuses', N'Admin', N'Dropdown option'),
    (N'All storage locations', N'QualityOrders', N'Dropdown option'),
    (N'All suppliers', N'QualityOrders', N'Dropdown option'),
    (N'Also attach', N'QualityOrders', N'Field label'),
    (N'Always CC', N'QualityOrders', N'Field label'),
    (N'An arrival has already been created for this container shipment:', N'Arrivals', N'Caption'),
    (N'Analyzer scope', N'Reports', N'Placeholder'),
    (N'Any cargo shifted / collapsed / water?', N'Arrivals', N'Caption'),
    (N'Any plant', N'Audit', N'Dropdown option'),
    (N'Any supplier', N'Audit', N'Dropdown option'),
    (N'Any user or role', N'Audit', N'Dropdown option'),
    (N'Anyone', N'QualityOrders', N'Dropdown option'),
    (N'Anything the report should mention -- weather, paperwork, special handling, etc.', N'Arrivals', N'Placeholder'),
    (N'Applied to any measure chip that has no format override.', N'Reports', N'Caption'),
    (N'Apply', N'Reports', N'Button'),
    (N'Apply filters', N'QualityOrders', N'Button'),
    (N'Approval note', N'ClaimManagement', N'Field label')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Arch', N'Arrivals', N'Caption'),
    (N'Archive by PO date', N'Arrivals', N'Heading'),
    (N'Archive by date', N'Arrivals', N'Button'),
    (N'Archive range', N'Arrivals', N'Button'),
    (N'Archived', N'Arrivals', N'Link'),
    (N'Arr', N'Arrivals', N'Caption'),
    (N'Arrival', N'QualityOrders', N'Column header'),
    (N'Arrival #', N'Arrivals', N'Field label'),
    (N'Arrival Date', N'Reports', N'Column header'),
    (N'Arrival Field Rules', N'Shared', N'Heading'),
    (N'Arrival Fields', N'Shared', N'Link'),
    (N'Arrival No', N'ClaimManagement', N'Column header'),
    (N'Arrival already exists', N'Arrivals', N'Heading'),
    (N'Arrival date', N'ClaimManagement', N'Field label'),
    (N'Arrival date from', N'Arrivals', N'Field label'),
    (N'Arrival date to', N'Arrivals', N'Field label'),
    (N'Arrival id', N'Reports', N'Field label'),
    (N'Arrival in Draft for more than N days triggers a warning.', N'Admin', N'Caption'),
    (N'Arrival no.', N'QualityOrders', N'Field label'),
    (N'Arrival pages', N'Arrivals', N'Placeholder'),
    (N'Arrival port', N'Arrivals', N'Field label'),
    (N'Arrival:', N'Arrivals', N'Field label'),
    (N'Arrivals', N'Shared', N'Heading'),
    (N'Arrivals Trend', N'Home', N'Field label'),
    (N'Arrivals in Draft', N'Home', N'Caption'),
    (N'Arrivals → Pending Containers', N'Admin', N'Link'),
    (N'Assessed by', N'ClaimManagement', N'Field label'),
    (N'Audit Log', N'Shared', N'Link'),
    (N'Auto', N'Reports', N'Dropdown option'),
    (N'Auto-create local profile on first successful AD login', N'Admin', N'Field label'),
    (N'Auto-sync', N'Admin', N'Column header'),
    (N'Available fields', N'Reports', N'Field label'),
    (N'Avatar', N'Account', N'Caption'),
    (N'Average — Σ value ÷ sample count (e.g. Gross / Net weight)', N'Admin', N'Dropdown option'),
    (N'Avg Defect %', N'Home', N'Caption'),
    (N'Awaiting Claim Manager decision', N'ClaimManagement', N'Caption'),
    (N'Awaiting checklist completion', N'Home', N'Caption'),
    (N'BOL', N'Arrivals', N'Field label'),
    (N'BOL No', N'Reports', N'Field label'),
    (N'BOL number', N'Arrivals', N'Field label'),
    (N'BOL:', N'QualityOrders', N'Field label'),
    (N'Back', N'QualityOrders', N'Link'),
    (N'Back (°C)', N'Arrivals', N'Field label'),
    (N'Back to QO', N'QualityOrders', N'Link'),
    (N'Back to arrivals', N'Arrivals', N'Link'),
    (N'Back to dashboard', N'Shared', N'Link'),
    (N'Background scheduler polls every minute; same hour will not trigger twice.', N'Admin', N'Caption'),
    (N'Basis for the report Time Bar', N'Arrivals', N'Caption'),
    (N'Batch', N'Arrivals', N'Column header'),
    (N'Become self', N'Shared', N'Button'),
    (N'Becomes', N'Admin', N'Column header'),
    (N'Before', N'Audit', N'Caption'),
    (N'Bill of Lading No.', N'Shared', N'Field label'),
    (N'Blue', N'Shared', N'Link'),
    (N'Body *', N'QualityOrders', N'Field label'),
    (N'Brand', N'Shared', N'Field label'),
    (N'Branding', N'Admin', N'Button'),
    (N'Brix', N'QualityOrders', N'Column header'),
    (N'Built fresh from the latest saved data.', N'QualityOrders', N'Caption'),
    (N'Built-in', N'Security', N'Caption'),
    (N'CC', N'QualityOrders', N'Field label'),
    (N'CMAU12…', N'Arrivals', N'Placeholder'),
    (N'Can open this screen', N'Security', N'Field label'),
    (N'Cancel', N'QualityOrders', N'Button'),
    (N'Cancel submit', N'QualityOrders', N'Button'),
    (N'Cancel — add samples first', N'QualityOrders', N'Button'),
    (N'Cancelled', N'Reports', N'Dropdown option'),
    (N'Capped by the first measure''s row total.', N'Reports', N'Caption'),
    (N'Cargo smell normal?', N'Arrivals', N'Caption'),
    (N'Carrier Name', N'Arrivals', N'Field label'),
    (N'Category', N'Shared', N'Field label'),
    (N'Category *', N'Admin', N'Field label'),
    (N'Change password', N'Account', N'Caption'),
    (N'Change plant', N'Arrivals', N'Placeholder'),
    (N'Changed by', N'Audit', N'Field label'),
    (N'Claim Status', N'ClaimManagement', N'Column header'),
    (N'Claim assessment', N'QualityOrders', N'Field label'),
    (N'Claim owner', N'ClaimManagement', N'Field label'),
    (N'Claim review', N'ClaimManagement', N'Field label'),
    (N'Claims', N'Shared', N'Link'),
    (N'Class', N'Reports', N'Field label'),
    (N'Class:', N'QualityOrders', N'Field label'),
    (N'Clear', N'QualityOrders', N'Link'),
    (N'Clear all', N'Audit', N'Link'),
    (N'Clear all filters', N'Reports', N'Link'),
    (N'Clear every row', N'Admin', N'Link'),
    (N'Clear selection', N'Reports', N'Button'),
    (N'Clear them', N'Audit', N'Link'),
    (N'Click to review pending', N'Home', N'Caption'),
    (N'Close', N'Reports', N'Button')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Closed', N'ClaimManagement', N'Column header'),
    (N'Closed By', N'ClaimManagement', N'Column header'),
    (N'Closed by', N'ClaimManagement', N'Field label'),
    (N'Closed from', N'ClaimManagement', N'Field label'),
    (N'Closed to', N'ClaimManagement', N'Field label'),
    (N'Code', N'Admin', N'Column header'),
    (N'Code *', N'Admin', N'Field label'),
    (N'Code Descriptions', N'Shared', N'Link'),
    (N'Collapse all', N'Security', N'Button'),
    (N'Colour', N'Admin', N'Field label'),
    (N'Columns', N'Reports', N'Caption'),
    (N'Comma- or semicolon-separated for multiple recipients.', N'QualityOrders', N'Caption'),
    (N'Comment', N'QualityOrders', N'Field label'),
    (N'Company branding for reports', N'Admin', N'Caption'),
    (N'Company logo', N'Admin', N'Caption'),
    (N'Company name', N'Admin', N'Field label'),
    (N'Compare all roles', N'Security', N'Link'),
    (N'Complete arrival', N'Arrivals', N'Button'),
    (N'Configure AD', N'Admin', N'Link'),
    (N'Confirm new password', N'Account', N'Field label'),
    (N'Confirm the commercial reasoning for approving this claim.', N'ClaimManagement', N'Placeholder'),
    (N'Contain (whole image visible)', N'Admin', N'Dropdown option'),
    (N'Container', N'Shared', N'Field label'),
    (N'Container No', N'Reports', N'Field label'),
    (N'Container ambiguous.', N'Arrivals', N'Caption'),
    (N'Container number', N'Arrivals', N'Field label'),
    (N'Container:', N'QualityOrders', N'Field label'),
    (N'Containers before this date are ignored. Set to your QMS go-live date.', N'Admin', N'Caption'),
    (N'Containers without Arrival', N'Home', N'Caption'),
    (N'Controls how the Quality Order PDF grouped summary renders this reading.', N'Admin', N'Caption'),
    (N'Copying is usually quicker than ticking a hundred boxes.', N'Security', N'Caption'),
    (N'Count of Materials', N'Shared', N'Field label'),
    (N'Count — number of samples with a value', N'Admin', N'Dropdown option'),
    (N'Country Of Origin', N'Shared', N'Field label'),
    (N'Country of origin', N'Arrivals', N'Field label'),
    (N'Cover (crop to fill)', N'Admin', N'Dropdown option'),
    (N'Coverage', N'Home', N'Column header'),
    (N'Create', N'Arrivals', N'Button'),
    (N'Create Quality Order', N'QualityOrders', N'Button'),
    (N'Create arrival', N'Arrivals', N'Button'),
    (N'Create role', N'Security', N'Button'),
    (N'Created', N'QualityOrders', N'Column header'),
    (N'Created By', N'Arrivals', N'Column header'),
    (N'Created by', N'Arrivals', N'Field label'),
    (N'Created from', N'QualityOrders', N'Field label'),
    (N'Created to', N'QualityOrders', N'Field label'),
    (N'Current folder in use', N'Admin', N'Field label'),
    (N'Current password', N'Account', N'Field label'),
    (N'Currently retrieving…', N'Arrivals', N'Field label'),
    (N'Custom column label (optional)', N'Reports', N'Field label'),
    (N'Customised', N'Admin', N'Caption'),
    (N'Dark', N'Shared', N'Link'),
    (N'Data Hub', N'Reports', N'Link'),
    (N'Data hub', N'Shared', N'Link'),
    (N'Date code', N'QualityOrders', N'Column header'),
    (N'Date — date picker', N'Admin', N'Dropdown option'),
    (N'Dates', N'Arrivals', N'Column header'),
    (N'Days since opened', N'Home', N'Caption'),
    (N'Default', N'Admin', N'Caption'),
    (N'Default unit', N'Admin', N'Field label'),
    (N'Defect', N'Reports', N'Column header'),
    (N'Defect % by Material Group', N'Home', N'Field label'),
    (N'Defect % red threshold', N'Admin', N'Field label'),
    (N'Defect % yellow threshold', N'Admin', N'Field label'),
    (N'Defect Catalog', N'Shared', N'Link'),
    (N'Defect Categories', N'Shared', N'Link'),
    (N'Defect Category', N'Reports', N'Column header'),
    (N'Defect Rate', N'Home', N'Field label'),
    (N'Defects per material group; the Category drives the Major/Minor split.', N'Admin', N'Caption'),
    (N'Delete', N'Reports', N'Button'),
    (N'Delete permanently', N'QualityOrders', N'Button'),
    (N'Delete sample', N'QualityOrders', N'Button'),
    (N'Delete selected', N'Admin', N'Button'),
    (N'Delete this role', N'Security', N'Button'),
    (N'Department', N'Security', N'Field label'),
    (N'Description', N'Security', N'Field label'),
    (N'Details incomplete', N'QualityOrders', N'Caption'),
    (N'Dimension', N'Reports', N'Field label'),
    (N'Disabled', N'Security', N'Dropdown option'),
    (N'Discharge Date', N'Shared', N'Field label'),
    (N'Discharge date', N'ClaimManagement', N'Field label'),
    (N'Display Temp (°C)', N'Arrivals', N'Field label'),
    (N'Documents', N'QualityOrders', N'Button'),
    (N'Domain *', N'Admin', N'Field label'),
    (N'Download', N'QualityOrders', N'Link'),
    (N'Download Excel', N'Reports', N'Caption'),
    (N'Download PDF report', N'QualityOrders', N'Link'),
    (N'Download checklist PDF', N'Arrivals', N'Link'),
    (N'Draft', N'Arrivals', N'Caption'),
    (N'Drag to resize. Allowed 50–400%.', N'Admin', N'Caption')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Drill / Filter', N'Reports', N'Caption'),
    (N'Drill filter', N'Reports', N'Caption'),
    (N'Drop photos here', N'Shared', N'Caption'),
    (N'EBELN', N'QualityOrders', N'Placeholder'),
    (N'Edit', N'Security', N'Button'),
    (N'Editable when closed', N'Admin', N'Column header'),
    (N'Editing a Completed arrival — only unlocked fields will change', N'Arrivals', N'Caption'),
    (N'Email', N'Security', N'Field label'),
    (N'Email (SMTP)', N'Admin', N'Button'),
    (N'Email / SMTP', N'Admin', N'Caption'),
    (N'Employee ID', N'Admin', N'Field label'),
    (N'Enable scheduled auto-sync', N'Admin', N'Field label'),
    (N'Enabled', N'Admin', N'Caption'),
    (N'Endpoint', N'Admin', N'Column header'),
    (N'Everything', N'Audit', N'Dropdown option'),
    (N'Examination date', N'Arrivals', N'Field label'),
    (N'Example', N'Admin', N'Column header'),
    (N'Expand all', N'Security', N'Button'),
    (N'Export pivot to Excel', N'Reports', N'Button'),
    (N'Export to Excel', N'Reports', N'Button'),
    (N'External damage', N'Shared', N'Field label'),
    (N'External damage to container / pallet?', N'Arrivals', N'Caption'),
    (N'Field', N'Admin', N'Column header'),
    (N'File', N'Shared', N'Column header'),
    (N'Filed away out of the pending list. Restore any of them.', N'Arrivals', N'Caption'),
    (N'Files', N'Shared', N'Field label'),
    (N'Filled', N'QualityOrders', N'Caption'),
    (N'Filter', N'Reports', N'Button'),
    (N'Filter by QC claim assessment', N'ClaimManagement', N'Placeholder'),
    (N'Filter by claim status', N'ClaimManagement', N'Placeholder'),
    (N'Filter by status', N'QualityOrders', N'Placeholder'),
    (N'Filter permissions…', N'Security', N'Placeholder'),
    (N'Filters', N'Reports', N'Caption'),
    (N'Finish Quality Order', N'QualityOrders', N'Heading'),
    (N'Finish note', N'ClaimManagement', N'Field label'),
    (N'Finish order', N'QualityOrders', N'Button'),
    (N'Finished', N'Reports', N'Dropdown option'),
    (N'Firmness', N'QualityOrders', N'Column header'),
    (N'Fit mode', N'Admin', N'Field label'),
    (N'Flat defects (data hub)', N'Reports', N'Heading'),
    (N'Footer line', N'Admin', N'Field label'),
    (N'Forest', N'Shared', N'Link'),
    (N'Forgot your password? Contact your administrator.', N'Account', N'Caption'),
    (N'Formula — placeholder, renders as “—” for now', N'Admin', N'Dropdown option'),
    (N'From', N'Home', N'Field label'),
    (N'From SAP (PO type)', N'Arrivals', N'Caption'),
    (N'From SAP (Receive_Date)', N'Arrivals', N'Caption'),
    (N'From email', N'Admin', N'Field label'),
    (N'From name', N'Admin', N'Field label'),
    (N'From this quality order and its arrival.', N'QualityOrders', N'Caption'),
    (N'Front (°C)', N'Arrivals', N'Field label'),
    (N'Full name', N'Security', N'Field label'),
    (N'Full name *', N'Account', N'Field label'),
    (N'Generating the QC report…', N'QualityOrders', N'Caption'),
    (N'Global', N'Admin', N'Caption'),
    (N'Grade', N'Shared', N'Field label'),
    (N'Group', N'Admin', N'Column header'),
    (N'Grower', N'QualityOrders', N'Column header'),
    (N'Hand over to Quality / Logistics?', N'Arrivals', N'Caption'),
    (N'Heat (per measure)', N'Reports', N'Field label'),
    (N'Hide 0s', N'Reports', N'Field label'),
    (N'Hold Notification', N'ClaimManagement', N'Button'),
    (N'Hours', N'Admin', N'Column header'),
    (N'How credentials are resolved:', N'Admin', N'Field label'),
    (N'I understand and want to finish this Quality Order.', N'QualityOrders', N'Field label'),
    (N'Identification fields entered per sample or per material.', N'Admin', N'Caption'),
    (N'If you add a comment, it appears as a message under your name on the claim page.', N'QualityOrders', N'Caption'),
    (N'Image / Thumbnail sizes', N'Admin', N'Caption'),
    (N'Images', N'Arrivals', N'Button'),
    (N'Images / Thumbnails', N'Admin', N'Button'),
    (N'Inactive', N'Security', N'Caption'),
    (N'Include per-sample detail', N'Audit', N'Field label'),
    (N'Initial', N'Reports', N'Dropdown option'),
    (N'Inspection', N'ClaimManagement', N'Caption'),
    (N'Inspection Checklist', N'Arrivals', N'Button'),
    (N'Inspection Date', N'Shared', N'Field label'),
    (N'Inspection date', N'ClaimManagement', N'Field label'),
    (N'Inspection point', N'Arrivals', N'Field label'),
    (N'Inspection summary', N'Arrivals', N'Caption'),
    (N'It cannot be undone.', N'QualityOrders', N'Caption'),
    (N'JPG / PNG / GIF / WEBP — max 10 MB each. Multiple files supported.', N'Shared', N'Caption'),
    (N'JPG / PNG / GIF / WEBP. Max 10 MB each.', N'Shared', N'Caption'),
    (N'Joint Survey', N'Shared', N'Field label'),
    (N'Justification note', N'ClaimManagement', N'Field label'),
    (N'Keep me signed in for 30 days', N'Account', N'Field label'),
    (N'Kind', N'Audit', N'Column header'),
    (N'Kind of change', N'Audit', N'Caption'),
    (N'LDAP path', N'Admin', N'Field label'),
    (N'Labels', N'Shared', N'Link'),
    (N'Last activity', N'ClaimManagement', N'Column header')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Last pull:', N'Admin', N'Field label'),
    (N'Last successful retrieval:', N'Arrivals', N'Field label'),
    (N'Last sync', N'Admin', N'Column header'),
    (N'Last sync:', N'Admin', N'Field label'),
    (N'Leave blank to keep existing password.', N'Admin', N'Caption'),
    (N'Leave blank to keep the saved password', N'Admin', N'Placeholder'),
    (N'Light', N'Shared', N'Link'),
    (N'Lines', N'Arrivals', N'Column header'),
    (N'Loading Date', N'Shared', N'Field label'),
    (N'Loading Port', N'Shared', N'Field label'),
    (N'Loading date', N'ClaimManagement', N'Field label'),
    (N'Loading photos…', N'QualityOrders', N'Caption'),
    (N'Loading port', N'ClaimManagement', N'Field label'),
    (N'Loading port:', N'QualityOrders', N'Field label'),
    (N'Loading sample…', N'QualityOrders', N'Caption'),
    (N'Loading:', N'Arrivals', N'Field label'),
    (N'Loading…', N'Reports', N'Caption'),
    (N'Locate and retrieve data logger?', N'Arrivals', N'Caption'),
    (N'Logger Serial', N'Shared', N'Field label'),
    (N'Logger serial', N'Arrivals', N'Field label'),
    (N'Logger temp (°C)', N'Arrivals', N'Field label'),
    (N'Logo size', N'Admin', N'Field label'),
    (N'Lot', N'QualityOrders', N'Column header'),
    (N'MSCUA…', N'Arrivals', N'Placeholder'),
    (N'Mail Template', N'Shared', N'Link'),
    (N'Major Cat', N'Reports', N'Column header'),
    (N'Major Category', N'Reports', N'Field label'),
    (N'Major Category:', N'QualityOrders', N'Field label'),
    (N'Major category', N'Arrivals', N'Column header'),
    (N'Major, Minor, Critical, … with display order and colour.', N'Admin', N'Caption'),
    (N'Manage on the Users screen', N'Security', N'Link'),
    (N'Mandatory', N'Admin', N'Field label'),
    (N'Mark as Claim Notification Request', N'ClaimManagement', N'Button'),
    (N'Mark as Passed QC', N'ClaimManagement', N'Button'),
    (N'Mark as Reviewed', N'ClaimManagement', N'Button'),
    (N'Material', N'Admin', N'Field label'),
    (N'Material Group', N'Shared', N'Field label'),
    (N'Material Group:', N'QualityOrders', N'Field label'),
    (N'Material details', N'QualityOrders', N'Button'),
    (N'Material group', N'Reports', N'Field label'),
    (N'Material group *', N'Admin', N'Field label'),
    (N'Material — entered once per material, inherited by every sample', N'Admin', N'Dropdown option'),
    (N'Materials', N'ClaimManagement', N'Field label'),
    (N'Materials without samples', N'QualityOrders', N'Heading'),
    (N'Measure', N'Reports', N'Field label'),
    (N'Measure to chart', N'Reports', N'Field label'),
    (N'Measurements captured per sample (Brix, Firmness, Net Weight, …).', N'Admin', N'Caption'),
    (N'Middle (°C)', N'Arrivals', N'Field label'),
    (N'Move container', N'Arrivals', N'Button'),
    (N'Move container to plant', N'Arrivals', N'Field label'),
    (N'Multi Carton', N'Reports', N'Dropdown option'),
    (N'My Profile', N'Shared', N'Heading'),
    (N'My image', N'Admin', N'Caption'),
    (N'Name', N'Reports', N'Field label'),
    (N'Name *', N'Admin', N'Field label'),
    (N'New arrival from SAP', N'Arrivals', N'Link'),
    (N'New password', N'Account', N'Field label'),
    (N'New password (min 6 chars)', N'Admin', N'Field label'),
    (N'New role', N'Security', N'Button'),
    (N'New sample size *', N'QualityOrders', N'Field label'),
    (N'Newest first', N'Audit', N'Caption'),
    (N'Next', N'Arrivals', N'Placeholder'),
    (N'No', N'Admin', N'Dropdown option'),
    (N'No Potential Claim', N'QualityOrders', N'Caption'),
    (N'No access', N'Security', N'Dropdown option'),
    (N'No audit history for this record or its children yet.', N'Audit', N'Caption'),
    (N'No defects configured for this category in Defect Catalog.', N'Shared', N'Caption'),
    (N'No defects configured for this material group.', N'QualityOrders', N'Caption'),
    (N'No documents uploaded yet.', N'Shared', N'Caption'),
    (N'No field-level differences were recorded.', N'Audit', N'Caption'),
    (N'No images uploaded yet.', N'Shared', N'Caption'),
    (N'No individual buttons on this screen.', N'Security', N'Caption'),
    (N'No logo uploaded', N'Admin', N'Caption'),
    (N'No matching SAP shipments. Adjust the filters and try again.', N'Arrivals', N'Caption'),
    (N'No material lines', N'Arrivals', N'Caption'),
    (N'No materials', N'QualityOrders', N'Caption'),
    (N'No open arrivals.', N'Home', N'Caption'),
    (N'No open quality orders.', N'Home', N'Caption'),
    (N'No reading types configured for this material group.', N'QualityOrders', N'Caption'),
    (N'No samples recorded yet for this material.', N'QualityOrders', N'Caption'),
    (N'No samples recorded yet — the summary appears once samples exist.', N'Shared', N'Caption'),
    (N'No users match the filters.', N'Admin', N'Caption'),
    (N'Nobody holds this role yet.', N'Security', N'Caption'),
    (N'Nobody ticked means nobody is mailed', N'Admin', N'Caption'),
    (N'None', N'Admin', N'Button'),
    (N'Not filled in', N'QualityOrders', N'Caption'),
    (N'Note', N'ClaimManagement', N'Field label'),
    (N'Notes', N'ClaimManagement', N'Column header'),
    (N'Nothing is archived. Containers you archive from the pending list land here.', N'Arrivals', N'Caption'),
    (N'Nothing matches that search.', N'Admin', N'Caption')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Nothing was received or committed in this period.', N'Home', N'Caption'),
    (N'Nothing — start with no permissions', N'Security', N'Dropdown option'),
    (N'Notifications', N'Shared', N'Link'),
    (N'Number format (fallback)', N'Reports', N'Field label'),
    (N'Number format (optional override)', N'Reports', N'Field label'),
    (N'Numeric', N'Admin', N'Dropdown option'),
    (N'Numeric — number input', N'Admin', N'Dropdown option'),
    (N'One Carton', N'Reports', N'Dropdown option'),
    (N'Only unlocked fields will change', N'Arrivals', N'Caption'),
    (N'Open', N'Reports', N'Column header'),
    (N'Open Arrivals', N'Home', N'Caption'),
    (N'Open QO Age', N'Home', N'Field label'),
    (N'Open QO not closed within N days triggers a warning.', N'Admin', N'Caption'),
    (N'Open Quality Order', N'Arrivals', N'Link'),
    (N'Open Quality Order days', N'Admin', N'Field label'),
    (N'Open Quality Orders', N'Home', N'Caption'),
    (N'Open existing arrival', N'Arrivals', N'Link'),
    (N'Open in new tab', N'QualityOrders', N'Link'),
    (N'Open with this perspective by default', N'Reports', N'Field label'),
    (N'Opened', N'Home', N'Column header'),
    (N'Opened By', N'QualityOrders', N'Column header'),
    (N'Opened by', N'QualityOrders', N'Field label'),
    (N'Optional', N'Admin', N'Caption'),
    (N'Optional. Server + base DN. Leave blank to use the domain.', N'Admin', N'Caption'),
    (N'Order', N'Admin', N'Column header'),
    (N'Order Status', N'ClaimManagement', N'Column header'),
    (N'Origin', N'Reports', N'Field label'),
    (N'Origin:', N'QualityOrders', N'Field label'),
    (N'Outstanding', N'Home', N'Column header'),
    (N'Override', N'QualityOrders', N'Caption'),
    (N'Override sample size (inspected qty)', N'QualityOrders', N'Heading'),
    (N'Override size', N'QualityOrders', N'Caption'),
    (N'PDF summary', N'Admin', N'Column header'),
    (N'PDF summary mode', N'Admin', N'Field label'),
    (N'PDF thumbnail height (px)', N'Admin', N'Field label'),
    (N'PDF thumbnail width (px)', N'Admin', N'Field label'),
    (N'PNG / JPG / GIF / WEBP, up to 2 MB.', N'Account', N'Caption'),
    (N'PO', N'Arrivals', N'Field label'),
    (N'PO (EBELN)', N'Arrivals', N'Field label'),
    (N'PO (Ebeln)', N'Reports', N'Field label'),
    (N'PO / Item', N'Arrivals', N'Column header'),
    (N'PO / STO', N'Arrivals', N'Column header'),
    (N'PO Date', N'Reports', N'Column header'),
    (N'PO Qty', N'Reports', N'Column header'),
    (N'PO Quantity', N'Shared', N'Field label'),
    (N'PO date from', N'Reports', N'Field label'),
    (N'PO date to', N'Reports', N'Field label'),
    (N'PO from', N'Reports', N'Field label'),
    (N'PO to', N'Reports', N'Field label'),
    (N'PO type', N'Arrivals', N'Field label'),
    (N'PO:', N'QualityOrders', N'Field label'),
    (N'Page 1 / 5', N'Admin', N'Caption'),
    (N'Page icon (browser tab favicon)', N'Admin', N'Caption'),
    (N'Pallet', N'QualityOrders', N'Column header'),
    (N'Parameters', N'Shared', N'Link'),
    (N'Password', N'Admin', N'Field label'),
    (N'Pending', N'Arrivals', N'Link'),
    (N'Pending Containers', N'Shared', N'Link'),
    (N'Pending Containers retrieval', N'Admin', N'Heading'),
    (N'Pending container pages', N'Arrivals', N'Placeholder'),
    (N'Pending or archived', N'Arrivals', N'Placeholder'),
    (N'Per-endpoint sync status', N'Admin', N'Caption'),
    (N'Per-sample entries are hidden.', N'Audit', N'Caption'),
    (N'Percentage', N'Shared', N'Column header'),
    (N'Period', N'Home', N'Placeholder'),
    (N'Permission', N'Security', N'Column header'),
    (N'Permissions', N'Security', N'Link'),
    (N'Person', N'Audit', N'Field label'),
    (N'Perspective analyzer', N'Reports', N'Field label'),
    (N'Photos', N'QualityOrders', N'Caption'),
    (N'Pivot the filtered data hub above into any cross-tab or chart.', N'Reports', N'Caption'),
    (N'Placeholder', N'Admin', N'Column header'),
    (N'Placeholders', N'Admin', N'Caption'),
    (N'Plain text. Newlines preserved. HTML is not rendered to the supplier.', N'Admin', N'Caption'),
    (N'Plain text. The PDF report is attached automatically.', N'QualityOrders', N'Caption'),
    (N'Plant', N'Home', N'Field label'),
    (N'Plant / Storage', N'Arrivals', N'Column header'),
    (N'Plants', N'Admin', N'Field label'),
    (N'Port', N'Admin', N'Field label'),
    (N'Port Of Arrival', N'Shared', N'Field label'),
    (N'Port of arrival', N'ClaimManagement', N'Field label'),
    (N'Port of arrival:', N'QualityOrders', N'Field label'),
    (N'Potential Claim', N'QualityOrders', N'Caption'),
    (N'Preparing email…', N'QualityOrders', N'Caption'),
    (N'Preview', N'Arrivals', N'Button'),
    (N'Preview QC report', N'QualityOrders', N'Button'),
    (N'Preview — top of the report:', N'Admin', N'Field label'),
    (N'Previous', N'Arrivals', N'Placeholder'),
    (N'Private', N'Reports', N'Caption'),
    (N'Procurement Type', N'Shared', N'Field label')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Procurement Type:', N'QualityOrders', N'Field label'),
    (N'Procurement type', N'ClaimManagement', N'Field label'),
    (N'Procurement types', N'Admin', N'Column header'),
    (N'Product', N'Shared', N'Field label'),
    (N'Products', N'ClaimManagement', N'Column header'),
    (N'Profile details', N'Account', N'Caption'),
    (N'Pull every (minutes)', N'Admin', N'Field label'),
    (N'Pull now', N'Admin', N'Button'),
    (N'Pull-out date', N'Arrivals', N'Field label'),
    (N'Pullout Date', N'Shared', N'Field label'),
    (N'Pulp F/M/B', N'Arrivals', N'Field label'),
    (N'Purch.Doc.', N'Shared', N'Field label'),
    (N'QC Assessment', N'ClaimManagement', N'Column header'),
    (N'QC assessment', N'ClaimManagement', N'Caption'),
    (N'QC created', N'Home', N'Column header'),
    (N'QC number', N'QualityOrders', N'Field label'),
    (N'QMS', N'Admin', N'Caption'),
    (N'QO', N'Reports', N'Column header'),
    (N'QO Number', N'QualityOrders', N'Column header'),
    (N'QO Status', N'Reports', N'Field label'),
    (N'QO id', N'Reports', N'Field label'),
    (N'QO-2026-000353 or 000353', N'Audit', N'Placeholder'),
    (N'QO-2026-000632 or 000632', N'QualityOrders', N'Placeholder'),
    (N'Qty', N'Arrivals', N'Column header'),
    (N'Quality Control Report', N'Admin', N'Caption'),
    (N'Quality Management System', N'Account', N'Caption'),
    (N'Quality Order', N'Arrivals', N'Column header'),
    (N'Quality Order report', N'Admin', N'Caption'),
    (N'Quality Orders', N'Shared', N'Heading'),
    (N'Quality Orders Open', N'Home', N'Caption'),
    (N'Quality Orders by Status', N'Home', N'Caption'),
    (N'Re-open arrival for edit', N'Arrivals', N'Heading'),
    (N'Re-open for edit', N'Arrivals', N'Button'),
    (N'Read only', N'Security', N'Dropdown option'),
    (N'Read-only AD account used for browsing the user list and the Test button.', N'Admin', N'Caption'),
    (N'Read-only — your role cannot change claim status.', N'ClaimManagement', N'Caption'),
    (N'Reading Types', N'Shared', N'Link'),
    (N'Readings', N'Shared', N'Caption'),
    (N'Reason', N'QualityOrders', N'Field label'),
    (N'Reason (required)', N'QualityOrders', N'Field label'),
    (N'Reason to hold', N'ClaimManagement', N'Field label'),
    (N'Receive Date', N'Shared', N'Field label'),
    (N'Receive date', N'Arrivals', N'Field label'),
    (N'Received', N'Home', N'Column header'),
    (N'Refresh', N'QualityOrders', N'Button'),
    (N'Refresh list', N'Security', N'Button'),
    (N'Remember', N'QualityOrders', N'Caption'),
    (N'Remember the first address for this supplier', N'QualityOrders', N'Field label'),
    (N'Remove current logo', N'Admin', N'Button'),
    (N'Remove uploaded image', N'Admin', N'Button'),
    (N'Renderer', N'Reports', N'Field label'),
    (N'Reopen', N'QualityOrders', N'Button'),
    (N'Reopen Quality Order', N'QualityOrders', N'Heading'),
    (N'Reopening creates an audit trail. Use only with proper justification.', N'QualityOrders', N'Caption'),
    (N'Report', N'Admin', N'Button'),
    (N'Report Builder', N'Reports', N'Heading'),
    (N'Report Location', N'Shared', N'Field label'),
    (N'Report Units', N'Shared', N'Link'),
    (N'Report builder', N'Shared', N'Link'),
    (N'Report layout', N'Admin', N'Field label'),
    (N'Report name', N'Reports', N'Field label'),
    (N'Report progress', N'QualityOrders', N'Placeholder'),
    (N'Reports', N'Shared', N'Link'),
    (N'Required', N'Admin', N'Caption'),
    (N'Required. Recorded in this Quality Order''s audit trail.', N'QualityOrders', N'Caption'),
    (N'Reset', N'Reports', N'Button'),
    (N'Reset these filters', N'QualityOrders', N'Link'),
    (N'Restore', N'Arrivals', N'Button'),
    (N'Restore by PO date', N'Arrivals', N'Heading'),
    (N'Restore by date', N'Arrivals', N'Button'),
    (N'Restore range', N'Arrivals', N'Button'),
    (N'Result', N'Admin', N'Column header'),
    (N'Retrieve latest containers', N'Arrivals', N'Button'),
    (N'Role', N'Admin', N'Field label'),
    (N'Role editor', N'Security', N'Link'),
    (N'Role name', N'Security', N'Field label'),
    (N'Roles', N'Security', N'Caption'),
    (N'Roles only', N'Audit', N'Dropdown option'),
    (N'Rose', N'Shared', N'Link'),
    (N'Rows', N'Reports', N'Column header'),
    (N'Run', N'Reports', N'Button'),
    (N'SAP OData', N'Admin', N'Button'),
    (N'SAP S/4HANA OData endpoints', N'Admin', N'Caption'),
    (N'SAP code', N'Admin', N'Field label'),
    (N'SAP containers without a QMS Arrival yet.', N'Arrivals', N'Caption'),
    (N'SAP search failed.', N'Arrivals', N'Caption'),
    (N'SAP sync needs attention.', N'Home', N'Caption'),
    (N'SAP user for this URL (blank = use global default)', N'Admin', N'Placeholder'),
    (N'SAP username', N'Admin', N'Field label'),
    (N'SMTP host', N'Admin', N'Field label')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'SMTP password', N'Admin', N'Field label'),
    (N'SMTP username', N'Admin', N'Field label'),
    (N'STO', N'Arrivals', N'Caption'),
    (N'Sailing:', N'Arrivals', N'Field label'),
    (N'Sample', N'QualityOrders', N'Caption'),
    (N'Sample #', N'Reports', N'Column header'),
    (N'Sample Headers', N'Shared', N'Link'),
    (N'Sample Scope', N'Reports', N'Field label'),
    (N'Sample Size', N'Shared', N'Field label'),
    (N'Sample defect % above this is a warning.', N'Admin', N'Caption'),
    (N'Sample defect % above this is critical.', N'Admin', N'Caption'),
    (N'Sample header', N'QualityOrders', N'Field label'),
    (N'Sample photos', N'QualityOrders', N'Caption'),
    (N'Sample size', N'Reports', N'Column header'),
    (N'Sample — entered on every sample', N'Admin', N'Dropdown option'),
    (N'Samples', N'Shared', N'Field label'),
    (N'Save', N'Reports', N'Button'),
    (N'Save AD settings', N'Admin', N'Button'),
    (N'Save SAP settings', N'Admin', N'Button'),
    (N'Save SMTP settings', N'Admin', N'Button'),
    (N'Save alert thresholds', N'Admin', N'Button'),
    (N'Save all roles', N'Security', N'Button'),
    (N'Save as…', N'Reports', N'Button'),
    (N'Save branding text', N'Admin', N'Button'),
    (N'Save changes', N'Account', N'Button'),
    (N'Save details', N'Security', N'Button'),
    (N'Save material details', N'QualityOrders', N'Button'),
    (N'Save override', N'QualityOrders', N'Button'),
    (N'Save perspective', N'Reports', N'Heading'),
    (N'Save recipients', N'Admin', N'Button'),
    (N'Save report options', N'Admin', N'Button'),
    (N'Save rules', N'Admin', N'Button'),
    (N'Save sample', N'QualityOrders', N'Button'),
    (N'Save settings', N'Admin', N'Button'),
    (N'Save shipment details', N'Arrivals', N'Button'),
    (N'Save storage folder', N'Admin', N'Button'),
    (N'Save template', N'Admin', N'Button'),
    (N'Save the sample first to enable photo uploads for it.', N'QualityOrders', N'Caption'),
    (N'Save thumbnail settings', N'Admin', N'Button'),
    (N'Save units', N'Admin', N'Button'),
    (N'Saved', N'Admin', N'Caption'),
    (N'Saved designs', N'Reports', N'Field label'),
    (N'Scheduled hours (24-hour clock, comma-separated)', N'Admin', N'Field label'),
    (N'Scope', N'Admin', N'Column header'),
    (N'Scope *', N'Admin', N'Field label'),
    (N'Screen', N'Security', N'Column header'),
    (N'Screen thumbnail height (px)', N'Admin', N'Field label'),
    (N'Screen thumbnail width (px)', N'Admin', N'Field label'),
    (N'Seal #', N'Arrivals', N'Field label'),
    (N'Seal Intact?', N'Shared', N'Field label'),
    (N'Seal No', N'Shared', N'Field label'),
    (N'Seal intact', N'Arrivals', N'Field label'),
    (N'Seal number matches documents?', N'Arrivals', N'Caption'),
    (N'Search', N'Audit', N'Field label'),
    (N'Search SAP', N'Arrivals', N'Button'),
    (N'Search SAP directly', N'Arrivals', N'Link'),
    (N'Search SAP shipment', N'Arrivals', N'Heading'),
    (N'Search by QO #, container, BOL, PO, supplier, or closed by...', N'ClaimManagement', N'Placeholder'),
    (N'Search domain by name, username, or email…', N'Admin', N'Placeholder'),
    (N'Search name, username, email...', N'Admin', N'Placeholder'),
    (N'Search screens and buttons…', N'Security', N'Placeholder'),
    (N'Search values', N'Reports', N'Field label'),
    (N'Search-only', N'Admin', N'Caption'),
    (N'Search…', N'Reports', N'Placeholder'),
    (N'Security', N'Shared', N'Link'),
    (N'Select all', N'Security', N'Button'),
    (N'Select all visible', N'Reports', N'Button'),
    (N'Send', N'QualityOrders', N'Button'),
    (N'Send report to supplier', N'QualityOrders', N'Button'),
    (N'Send test', N'Admin', N'Button'),
    (N'Send test email to', N'Admin', N'Field label'),
    (N'Sepia', N'Shared', N'Link'),
    (N'Service account password', N'Admin', N'Field label'),
    (N'Service account user', N'Admin', N'Field label'),
    (N'Set / Display temp', N'Arrivals', N'Field label'),
    (N'Set Temp (°C)', N'Arrivals', N'Field label'),
    (N'Set as default', N'Reports', N'Button'),
    (N'Sharbatly QMS', N'Account', N'Heading'),
    (N'Sharbatly Quality Management System', N'Home', N'Caption'),
    (N'Shared', N'Reports', N'Field label'),
    (N'Shipment', N'QualityOrders', N'Button'),
    (N'Shipment Details', N'Shared', N'Caption'),
    (N'Shipment details', N'ClaimManagement', N'Placeholder'),
    (N'Shipment identity', N'Arrivals', N'Caption'),
    (N'Shipper', N'Shared', N'Field label'),
    (N'Shipping Date', N'Reports', N'Column header'),
    (N'Show', N'Arrivals', N'Field label'),
    (N'Show all records', N'QualityOrders', N'Link'),
    (N'Showing a filtered list.', N'QualityOrders', N'Caption'),
    (N'Showing the first 200 values — refine your search to narrow the list.', N'Reports', N'Caption')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Shown in the Claims window so claims can be picked up faster.', N'QualityOrders', N'Caption'),
    (N'Shown on the Users screen. The internal code is generated for you.', N'Security', N'Caption'),
    (N'Sign in', N'Account', N'Button'),
    (N'Sign out', N'Shared', N'Button'),
    (N'Site Configuration', N'Shared', N'Heading'),
    (N'Site Configuration → SAP', N'Home', N'Link'),
    (N'Site URL (used in email links)', N'Admin', N'Field label'),
    (N'Site name', N'Admin', N'Field label'),
    (N'Size', N'Shared', N'Column header'),
    (N'Size:', N'QualityOrders', N'Field label'),
    (N'Soft', N'Admin', N'Caption'),
    (N'Something went wrong', N'Shared', N'Heading'),
    (N'Sort order', N'Admin', N'Field label'),
    (N'Spelling matters.', N'Admin', N'Caption'),
    (N'Stale Arrivals', N'Home', N'Caption'),
    (N'Stale arrival (Draft) days', N'Admin', N'Field label'),
    (N'Start date (Doc_Date ≥)', N'Admin', N'Field label'),
    (N'Start from', N'Security', N'Field label'),
    (N'Status', N'Arrivals', N'Field label'),
    (N'Stop previewing', N'Shared', N'Button'),
    (N'Storage', N'Arrivals', N'Column header'),
    (N'Storage Loc', N'Reports', N'Field label'),
    (N'Storage Loc.', N'Reports', N'Field label'),
    (N'Storage location', N'ClaimManagement', N'Field label'),
    (N'Sub Cat', N'Reports', N'Column header'),
    (N'Sub-Major Category:', N'QualityOrders', N'Field label'),
    (N'Subject', N'Audit', N'Caption'),
    (N'Subject *', N'QualityOrders', N'Field label'),
    (N'Subject and body used when sending the QO report to suppliers.', N'Admin', N'Caption'),
    (N'Submit', N'QualityOrders', N'Button'),
    (N'Submitted', N'Reports', N'Dropdown option'),
    (N'Sum — total of numeric values', N'Admin', N'Dropdown option'),
    (N'Summary', N'QualityOrders', N'Button'),
    (N'Supplier', N'Reports', N'Field label'),
    (N'Supplier (name contains)', N'Reports', N'Field label'),
    (N'Sync Status', N'Admin', N'Button'),
    (N'Sync now', N'Admin', N'Button'),
    (N'Takes effect on the next page anyone loads — no sign-out needed.', N'Security', N'Caption'),
    (N'Takes effect on the next report you generate.', N'Admin', N'Caption'),
    (N'Tara Weight', N'Shared', N'Field label'),
    (N'Tare exceeds gross — net can''t be negative.', N'QualityOrders', N'Caption'),
    (N'Tare weight', N'QualityOrders', N'Field label'),
    (N'Technical detail', N'Audit', N'Caption'),
    (N'Temperature', N'Shared', N'Field label'),
    (N'Temperature Unit Reading', N'Arrivals', N'Caption'),
    (N'Test', N'Arrivals', N'Button'),
    (N'Test connection', N'Admin', N'Button'),
    (N'Text', N'Admin', N'Dropdown option'),
    (N'Text join — distinct values, comma-separated', N'Admin', N'Dropdown option'),
    (N'Text — free text input', N'Admin', N'Dropdown option'),
    (N'The Administrator is a super role.', N'Security', N'Caption'),
    (N'The field only appears on arrivals whose materials contain this group.', N'Admin', N'Caption'),
    (N'The quality order also disappears from Data Hub and the Perspective Analyzer.', N'QualityOrders', N'Caption'),
    (N'The same storage-location code exists under several plants, so it needs one.', N'Admin', N'Caption'),
    (N'Theme', N'Shared', N'Heading'),
    (N'Theme picker', N'Shared', N'Placeholder'),
    (N'This cannot be undone.', N'Arrivals', N'Caption'),
    (N'This is your own role.', N'Security', N'Caption'),
    (N'Throughput vs QC pace', N'Home', N'Field label'),
    (N'Tick each photo as you capture it. Actual files are uploaded on the Images tab.', N'Arrivals', N'Caption'),
    (N'Ticking nothing means everything', N'Admin', N'Caption'),
    (N'Time Bar Exceeded', N'Arrivals', N'Field label'),
    (N'Time Bar basis', N'Admin', N'Field label'),
    (N'Time bar (days)', N'Arrivals', N'Field label'),
    (N'Timeline', N'ClaimManagement', N'Caption'),
    (N'To', N'Home', N'Field label'),
    (N'To *', N'QualityOrders', N'Field label'),
    (N'Top N rows', N'Reports', N'Field label'),
    (N'Total', N'Shared', N'Caption'),
    (N'Transit', N'Arrivals', N'Column header'),
    (N'Transit Days', N'Shared', N'Field label'),
    (N'Transit days', N'Arrivals', N'Field label'),
    (N'Transit days:', N'QualityOrders', N'Field label'),
    (N'Type', N'QualityOrders', N'Field label'),
    (N'Unit', N'Admin', N'Column header'),
    (N'Unit on report', N'Admin', N'Column header'),
    (N'Unloading Date', N'Shared', N'Field label'),
    (N'Unloading date', N'Arrivals', N'Field label'),
    (N'UoM', N'Arrivals', N'Column header'),
    (N'Update password', N'Account', N'Button'),
    (N'Updated', N'Admin', N'Column header'),
    (N'Upload', N'Shared', N'Button'),
    (N'Upload documents', N'Shared', N'Caption'),
    (N'Upload images', N'Shared', N'Caption'),
    (N'Upload new logo', N'Admin', N'Field label'),
    (N'Upload picture', N'Account', N'Button'),
    (N'Upload yours', N'Admin', N'Caption'),
    (N'Uploaded', N'Shared', N'Column header'),
    (N'Uploaded by', N'Shared', N'Column header'),
    (N'Uploaded photo storage', N'Admin', N'Caption')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'Uploads disk full alert (%)', N'Admin', N'Field label'),
    (N'Uploads folder (absolute path)', N'Admin', N'Field label'),
    (N'Use TLS / SSL', N'Admin', N'Field label'),
    (N'Used for the section banner in the form and PDF.', N'Admin', N'Caption'),
    (N'User', N'Admin', N'Caption'),
    (N'Username', N'Security', N'Field label'),
    (N'Users', N'Shared', N'Heading'),
    (N'Users and roles', N'Audit', N'Dropdown option'),
    (N'Users only', N'Audit', N'Dropdown option'),
    (N'Value', N'Reports', N'Column header'),
    (N'Value kind *', N'Admin', N'Field label'),
    (N'Value type', N'Admin', N'Column header'),
    (N'Value type *', N'Admin', N'Field label'),
    (N'Values', N'Reports', N'Caption'),
    (N'Variety', N'Shared', N'Field label'),
    (N'Variety:', N'QualityOrders', N'Field label'),
    (N'Vendor', N'Arrivals', N'Field label'),
    (N'Vendor No (exact)', N'Reports', N'Field label'),
    (N'Vendor:', N'QualityOrders', N'Field label'),
    (N'Vessel / Voyage', N'ClaimManagement', N'Field label'),
    (N'Vessel Name', N'Shared', N'Field label'),
    (N'Vessel name', N'Arrivals', N'Field label'),
    (N'Vessel:', N'QualityOrders', N'Field label'),
    (N'View', N'Arrivals', N'Column header'),
    (N'View arrival', N'QualityOrders', N'Link'),
    (N'View claim details', N'ClaimManagement', N'Placeholder'),
    (N'View site as', N'Shared', N'Heading'),
    (N'Viewer', N'Admin', N'Caption'),
    (N'Visibility', N'Reports', N'Field label'),
    (N'Visible to both Quality Manager and Claim Manager.', N'ClaimManagement', N'Caption'),
    (N'Visual cargo OK', N'Arrivals', N'Field label'),
    (N'Visual cargo acceptable', N'Shared', N'Field label'),
    (N'Visual cargo condition acceptable?', N'Arrivals', N'Caption'),
    (N'Voyage number', N'Arrivals', N'Field label'),
    (N'Voyage:', N'Arrivals', N'Field label'),
    (N'Weight:', N'QualityOrders', N'Field label'),
    (N'What changed', N'Audit', N'Caption'),
    (N'What happened', N'Audit', N'Column header'),
    (N'What is this role for?', N'Security', N'Placeholder'),
    (N'When', N'Audit', N'Column header'),
    (N'Which records', N'Audit', N'Caption'),
    (N'Who and when', N'Audit', N'Caption'),
    (N'Who changed what, in plain words', N'Audit', N'Caption'),
    (N'Who is emailed when a quality order is finished', N'Admin', N'Caption'),
    (N'Why does this QO need a claim notification to the supplier?', N'ClaimManagement', N'Placeholder'),
    (N'Why does this QO not require a claim?', N'ClaimManagement', N'Placeholder'),
    (N'Why is the arrival being re-opened?', N'Arrivals', N'Placeholder'),
    (N'Why is the claim being held?', N'ClaimManagement', N'Placeholder'),
    (N'Yes', N'Admin', N'Dropdown option'),
    (N'Yes / No — dropdown', N'Admin', N'Dropdown option'),
    (N'You don''t have permission to view this page.', N'Account', N'Caption'),
    (N'all', N'Reports', N'Caption'),
    (N'any part', N'QualityOrders', N'Placeholder'),
    (N'archived', N'Arrivals', N'Caption'),
    (N'auto', N'QualityOrders', N'Caption'),
    (N'beta', N'Reports', N'Caption'),
    (N'cannot be modified', N'QualityOrders', N'Caption'),
    (N'changed to', N'Shared', N'Placeholder'),
    (N'code or description', N'QualityOrders', N'Placeholder'),
    (N'count column header', N'Admin', N'Caption'),
    (N'dc1.sharbatly.local/DC=sharbatly,DC=local', N'Admin', N'Placeholder'),
    (N'domain credentials', N'Admin', N'Caption'),
    (N'drag chips up/down to reorder · × to remove', N'Reports', N'Caption'),
    (N'e.g. 2, 14', N'Admin', N'Placeholder'),
    (N'e.g. Air Shipment', N'Admin', N'Placeholder'),
    (N'e.g. Apple defects by container', N'Reports', N'Placeholder'),
    (N'e.g. CMAU1234567', N'Arrivals', N'Placeholder'),
    (N'e.g. MSCUAB1234', N'Arrivals', N'Placeholder'),
    (N'e.g. Major, Minor, Critical, Progressive.', N'Admin', N'Caption'),
    (N'e.g. Night Shift Inspector', N'Security', N'Placeholder'),
    (N'e.g. Supplier sample not available; proceeding with QM approval', N'QualityOrders', N'Placeholder'),
    (N'e.g. Total defects', N'Reports', N'Placeholder'),
    (N'e.g. arabian', N'Reports', N'Placeholder'),
    (N'e.g. mohamed.tag', N'Account', N'Placeholder'),
    (N'every', N'Admin', N'Caption'),
    (N'everything under it', N'QualityOrders', N'Caption'),
    (N'http://localhost:5300', N'Admin', N'Placeholder'),
    (N'kg, °C, …', N'Admin', N'Placeholder'),
    (N'not', N'QualityOrders', N'Caption'),
    (N'optional', N'Reports', N'Placeholder'),
    (N'optional, comma-separated', N'QualityOrders', N'Placeholder'),
    (N'part of the name', N'Arrivals', N'Placeholder'),
    (N'part of the number is enough', N'Audit', N'Placeholder'),
    (N'pending', N'Arrivals', N'Caption'),
    (N'per page', N'Arrivals', N'Caption'),
    (N'read-only or edit', N'Security', N'Caption'),
    (N'report.pdf', N'QualityOrders', N'Caption'),
    (N'retired', N'Security', N'Caption'),
    (N'sharbatly.local', N'Admin', N'Placeholder'),
    (N'show more / less', N'Audit', N'Link')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO

MERGE qms.qms_ui_label AS t
USING (VALUES
    (N'smtp.sendgrid.net', N'Admin', N'Placeholder'),
    (N'svc-qms', N'Admin', N'Placeholder'),
    (N'this supplier', N'QualityOrders', N'Caption'),
    (N'to', N'Home', N'Caption'),
    (N'type to filter…', N'Reports', N'Placeholder'),
    (N'user, role, permission…', N'Audit', N'Placeholder'),
    (N'username, or several separated by commas', N'Audit', N'Placeholder'),
    (N'view / export', N'Security', N'Caption'),
    (N'was', N'Arrivals', N'Caption'),
    (N'— all —', N'Reports', N'Dropdown option'),
    (N'— drag fields here; order top-to-bottom = left-to-right in Excel', N'Reports', N'Caption'),
    (N'— new report —', N'Reports', N'Dropdown option'),
    (N'— pick a group —', N'Reports', N'Dropdown option'),
    (N'— pick the owning plant —', N'Admin', N'Dropdown option'),
    (N'— sample cannot be saved unless this field has a value', N'Admin', N'Caption'),
    (N'— sample cannot be saved unless this reading has a value', N'Admin', N'Caption'),
    (N'🌐 Global — applies to every material group', N'Admin', N'Dropdown option')
) AS s (label_key, screen_key, kind)
    ON t.label_key = s.label_key
WHEN MATCHED THEN
    UPDATE SET kind       = s.kind,
               screen_key = COALESCE(t.screen_key, NULLIF(s.screen_key, N''))
WHEN NOT MATCHED THEN
    INSERT (label_key, screen_key, kind)
    VALUES (s.label_key, NULLIF(s.screen_key, N''), s.kind);
GO


SELECT 'labels_total' AS check_item, CAST(COUNT(*) AS VARCHAR(20)) AS value FROM qms.qms_ui_label
UNION ALL SELECT 'classified',  CAST(COUNT(*) AS VARCHAR(20)) FROM qms.qms_ui_label WHERE kind IS NOT NULL
UNION ALL SELECT 'overridden',  CAST(COUNT(*) AS VARCHAR(20)) FROM qms.qms_ui_label WHERE custom_text IS NOT NULL;
GO

SELECT kind AS check_item, CAST(COUNT(*) AS VARCHAR(20)) AS value
FROM   qms.qms_ui_label GROUP BY kind ORDER BY COUNT(*) DESC;
GO
